### ISSUE TITLE
Google etc. integration without relying on onlyoffice.com servers?

### ISSUE THREAD

**Issue by poVoq** [ONLYOFFICE/CommunityServer#102]
Hello!

First off, really nice work on this Community server :)

I am wondering though if it is possible somehow to add the 3rd party service integration somehow without relying on the https://service.onlyoffice.com/oauth2.aspx call back URL?

It is working fine as a test with my local Docker instance, but I am somewhat concerned that this might be an issue with EU privacy laws and data security? Because basically people are giving for example their google drive permissions to OnlyOffice then? Or am I misunderstanding how this works?

I tested: https://mycommunityserverurl/oauth2.aspx instead, but that isn't working at all.

Thanks for the help!

**Comment by LinneyS** [comment]
You can download the source code of the static page `https://service.onlyoffice.com/oauth2.aspx` and place it on your own server.
Then replace the addresses in the file https://github.com/ONLYOFFICE/CommunityServer/blob/master/web/studio/ASC.Web.Studio/Web.consumers.config

**Comment by poVoq** [comment]
Hmm, I assume this needs a webserver running asp.net/mono?

I tried placing it in the /var/www/onlyoffice/WebStudio folder of the Docker image that that results in a server error.

**Comment by LinneyS** [comment]
Try to rename `oauth2.aspx`  to `oauth2.html`

**Comment by poVoq** [comment]
That... actually worked. Still had to restart the server after editing the web.consumers.config, but then it connected fine with google.

Thanks a lot!

**Comment by VincentSC** [comment]
In Docker `nano`, `sed` and `wget` are installed. So these are the steps:

> wget -O /var/www/onlyoffice/WebStudio/oauth.html https://service.onlyoffice.com/oauth2.aspx

> sed -i 's/service\.onlyoffice\.com\/oauth2\.aspx/your\.domain\.com\/oauth2\.html/g' /var/www/onlyoffice/WebStudio/web.consumers.config
