### ISSUE TITLE
send mail problems

### ISSUE THREAD

**Issue by platix** [ONLYOFFICE/CommunityServer#11]
The webmail addon of the owner of the portal ignores the configured account SMTP settings.
When I send an email to gmail, it's return :
mail-daemon@teamlab.com
This message was created automatically by mail delivery software.

Delivery failed for message with subject "subject" from 05/15/2015 22:49:45.

Message could not be delivered to recipient(s):

gmail_account@gmail.com
Please, check your message recipients addresses and message format. If you are sure your message is correct, check all the owner@account.com account settings, and, if everything is correct, sign in to the mail service you use and confirm any verification questions, in case there are some. After then try again.

Razón: "The remote server returned an error: (404) Not Found."

On other account, it's works well.

Also, the global SMTP configured is ignored by the system when I request an activation email on new accounts.

**Comment by AnaMih** [comment]
1) Could you please specify the custom smtp settings (Settings-> Integration->SMTP Settings)
"Also, the global SMTP configured is ignored by the system when I request an activation email on new accounts."
Do you have that issue while sending the activation email to any email address with different domain names?
Also try to send invitation letter using default smtp setting (after changing settings we'd recommend to restart Notify service)

2) Please describe your actions step by step before receiving "Delivery failed" message
"On other account, it's works well."
Btw specify the account
