### ISSUE TITLE
monoserve must be reloaded when webpages are not full charged

### ISSUE THREAD

**Issue by ndecaris** [ONLYOFFICE/CommunityServer#111]
after couple of weeks working well, webpages from community server are not completed (miss some contents : like css file, ...). we need to restart monoserve daemon (we work on ubuntu server 16.04).
 nothing in the logs : so how to debug those kind of behaviour ?

thank you in advance

**Comment by Carazyda** [comment]
Can you provide screenshots of webpages with opened browser console? You use latest versions of community server? Deb package? After restart monoserve problem has gone away for a couple weeks?

**Comment by ndecaris** [comment]
here is a screenshot :
![bug-oo-webpages](https://user-images.githubusercontent.com/24547534/44260625-4b87bd00-a215-11e8-80f1-98f0b00f6c1a.png)

we use this version : 9.6.1.627

yes, we install on Ubuntu Server 16.04 with official deb package.

yes restart monoserve resolves the issue for a couple of weeks.

in which logs can we debug this kind of issues ?

Thank you

**Comment by Carazyda** [comment]
Looks like "bundle" folder crashed. You don't touch this? It's enough free space on hdd? Also you can try to remove this folder (/var/www/onlyoffice/Data/bundle) and restart monoserve. This will slow down your portal for first open, but further all works fine.

**Comment by ndecaris** [comment]
ok thank you for the advice. what is included in this folder ?

**Comment by Carazyda** [comment]
Compiled css and js scripts. Usually everything go fine, but in extraordinary case, this folder can be broken. Remove and restart will help.
