### ISSUE TITLE
Spreadsheet application should support HYPERLINK function

### ISSUE THREAD

**Issue by NoUsername** [ONLYOFFICE/CommunityServer#114]
The hyperlink function is a really useful tool in google sheets, which allows you to generate links based on data from other cells.
Checked the documentation, but it seems only static hyperlinks (via the hyperlink-popup) can be created in onlyoffice.

a function like:

    =HYPERLINK("https://github.com/ONLYOFFICE/CommunityServer/issues/" & B2, "Issue")

would be really helpful

**Comment by ShockwaveNN** [comment]
This is CommunityServer issue tracker. Please duplicate your issue in https://github.com/ONLYOFFICE/DocumentServer/issues
