### ISSUE TITLE
Mail is not deleted from source server after being deleted from Mail

### ISSUE THREAD

**Issue by Daniel-Beardsmore** [ONLYOFFICE/CommunityServer#124]
The mail aggregator does not actually delete mail from the source server when it is deleted from the aggregator. This occurs with both the Docker mail server component (when fully integrated into Community Server) and when aggregating mail from an external mail server with IMAP.

If a mailbox on the local Docker mail server receives mail, and you delete that mail, the messages are not cleared from the mailbox folder in /var/vmail/vmail1/domain/s/o/m/some.mailbox/Maildir/new.

When using the Docker mail server, this is worse, as this is not actually aggregation but a "real" hosted mail service (but one that is being accessed by an aggregator when Community Server should really have an IMAP client), and there is no other access into those mailboxes, so delete should actually delete, but it doesn't.

It's possible that the IMAP purge is not being issued, but on another mail system, the messages deleted from Community Server Mail did not even show as deleted (struck through) and waiting purge.

OO 9.6.3.663

**Comment by Carazyda** [comment]
Hello @Daniel-Beardsmore we released this in 10.0 version of Community Server. Also plans to implement work directly with the Mail Server, without an aggregator.

**Comment by Daniel-Beardsmore** [comment]
10 doesn't appear to be released yet; what did you change?

**Comment by Daniel-Beardsmore** [comment]
10 doesn't appear to be released yet; what did you change?

(I notice that https://helpcenter.onlyoffice.com/server/community/changelog.aspx is also out of date.)

**Comment by Daniel-Beardsmore** [comment]
I meant that it is not showing the latest v9 release (let alone 10).

**Comment by Carazyda** [comment]
9.6.4 is our latest release, with minor bugfix. We will update this in changelog. Changes of 10.0 will published after release of this.
