### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by solloron1** [ONLYOFFICE/CommunityServer#130]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
The user has full access to files uploaded
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Wondering if it is possible to make it so they can do everything with the files but delete them?
**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
5.2.3
**Operating System:**
Cent OS 7
**Browser version:**
Chrome 70.0.3538.102

**Comment by HelenBelova17** [comment]
Hello, **@solloron1**, do you use module Documents? What submodule? Can you describe step by step your action?

**Comment by solloron1** [comment]
Yes we use the Documents module. I don't believe we are using any sub modules.

What we are trying to do is make it so any user can create, edit and read files we just want to take away the ability of deleting files they create.

User creates file
User edits file
User try's to delete file but is unable to. 
Would like it so only an administrator can do that.

**Comment by solloron1** [comment]
No. The common documents work as intended I believe.

What I would like to be able to do is prevent users from deleting documents in their "My Documents" folder on Onlyoffice. Currently there are no permissions like that.

We want them to be able to read and write, just not delete.

**Comment by HelenBelova17** [comment]
Here, https://helpcenter.onlyoffice.com/gettingstarted/documents.aspx -> Overview in description: “‘My Documents’ is a private storage space, each portal member (with the exception of guests) has this section where he can upload, import or create documents for personal use only”. We don't plan to change this functionality in the near future.

**Comment by solloron1** [comment]
Ok thank you for clearing it up. Is that different on the Enterprise edition?

**Comment by HelenBelova17** [comment]
In Enterprise edition the same.
