### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by GarryLai** [ONLYOFFICE/CommunityServer#131]
An Error message show ud and build fail
> DbSender\MessagesRepository.cs(48,31): error CS0012: 類型 'System.Object' 是定義在未參考的組件中。您必須加入參考至組件 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'。
Please help me to solve it

**Comment by Carazyda** [comment]
Hello @GarryLai what are you build and what instruction do you use? What OS and hardware? Please describe more details.

**Comment by GarryLai** [comment]
Oh, I solved it, I forgot to install the .net4.6.2 development pack, thank you.

**Comment by GarryLai** [comment]
Oh, I solved it, I forgot to install the .net4.6.2 development pack, thank you.

**Comment by Carazyda** [comment]
Yes, it is necessary. Thank you for interest our product!
