### ISSUE TITLE
Can I use a Enterprise License on this edition?

### ISSUE THREAD

**Issue by GarryLai** [ONLYOFFICE/CommunityServer#132]
Can I use a Enterprise License on the opensource edition?

**Comment by Carazyda** [comment]
No, enterprise license only for Enterprise Edition. Why you need for this? All information you can find in our [site](https://www.onlyoffice.com/enterprise-edition.aspx).

**Comment by Carazyda** [comment]
> We want to buy a license to use, but we also need to modify the code to meet our requirements.
In theory it possible. Please contact our sales department - sales@onlyoffice.com, for more details.

Yes, white label is only in EE or SaaS.

**Comment by GarryLai** [comment]
My question is that you say the license can't use in opensource edition,
but why the code about white label is on Github?

It means that I can use the license to unlock that function??

Mike Grunin <notifications@github.com> 於 2018年12月4日 週二 下午9:45 寫道：

**Comment by Carazyda** [comment]
Code is on github, in community server, but interface for using the white label is in Control Panel, and available only in Enterprise Edition.

**Comment by kingqiuxiang** [comment]
THE LENSE GPL V3 OR APGPLV3???

**Comment by Carazyda** [comment]
> THE LENSE GPL V3 OR APGPLV3???

License for Community Server is GNU GPL v3.0.

**Comment by zzk1314** [comment]
> > THE LENSE GPL V3 OR APGPLV3???
> 
> License for Community Server is GNU GPL v3.0.

Now, the license change to AGPL ? where is saw on README.md
