### ISSUE TITLE
Multitenancing - Wrong Logo in mail notification

### ISSUE THREAD

**Issue by czerr** [ONLYOFFICE/CommunityServer#136]
Hi guys,

I buy and have ONLYOFFICE Enterprise Standard+ installed on W2012R2.

I have over 10 portals in multitenancing with specific logo for each portal (white label)

When i am on a portal and i create a user, the user receive the mail with good links to join the portal but the logo is wrong (not the good logo for the portal) ...

Thanks for your answer (and excuse me for my bad english) 

Christophe

**Comment by czerr** [comment]
![good-logo-for-the-portal](https://user-images.githubusercontent.com/491630/50232226-ba864580-03b0-11e9-8dc5-18ce06e3ed36.jpg)
![wrong-logo-in-mail-notification](https://user-images.githubusercontent.com/491630/50232254-cc67e880-03b0-11e9-910d-25e417b9001c.jpg)

**Comment by Carazyda** [comment]
Hello @czerr  sorry for the late answer. We detected a problem, and will fixed it in 10 version of Onlyoffice. Thank you for a advice!

**Comment by czerr** [comment]
Hi Mike,
Okay. Thank you for your reply. So, I'm waiting for the release of the v10.
Christophe
