### ISSUE TITLE
[FR] Ctrl + backspace

### ISSUE THREAD

**Issue by FoseFx** [ONLYOFFICE/CommunityServer#139]
In most of the editors I use Ctrl + backspace removes the word behind the cursor:
`somet|est => est`, `this is some| test => this is test`, `wow| => `
In OO it doesn't and this really bothers me.

**Comment by Carazyda** [comment]
Hello @FoseFx  please transfer your issue in https://github.com/ONLYOFFICE/DocumentServer

Community Server not included function of editors.
