### ISSUE TITLE
MailAggregator don't remove deleted accounts from disk

### ISSUE THREAD

**Issue by platix** [ONLYOFFICE/CommunityServer#14]
I deleted email accounts when they are downloading emails via IMAP and the files in "/var/www/onlyoffice/Data/addons/mail/Data/aggregator/" have not been deleted.

On the other hand, is it possible to know the status of the complete implementation of IMAP?(sync, folders,...) We are going to stop using this wonderful software because we need it.

Best regards

**Comment by AnaMih** [comment]
Deletion of the files may take a long time, longer than 30 sec (api execution time)
We are currently working on the service for removal unnecessary  files.
We also have plans to add an advanced cleaning service for complete deletion of portal information
