### ISSUE TITLE
No way to edit groups in People module

### ISSUE THREAD

**Issue by dokterbob** [ONLYOFFICE/CommunityServer#148]
There's no way to edit the name or other properties of groups in the People module.

**Comment by andreysavihin** [comment]
![t-B6uwEJTNW4tktrvFkg5w](https://user-images.githubusercontent.com/8580529/55540831-72bfcb80-56cc-11e9-9e5e-8819a7b62d06.png)

**Comment by andreysavihin** [comment]
Of course, you must have admins rights :-)

**Comment by dokterbob** [comment]
@andreysavihin Thanks again for super quick reply!

Wow that was *well* hidden away! I literally looked 3x for like 10 minutes.

Same as with other issues, I really do think it's a UI problem. It seems to me there is plenty of screen real estate on desktop UI's to allow for icon buttons.
![buttons](https://user-images.githubusercontent.com/22742/55546587-8fa5d000-56c7-11e9-99d0-679c5b1b2fac.png)

**Comment by Medanna** [comment]
Hi @dokterbob, thank you for your remark. We are already in progress with the UI-optimizing and will take your opinion into consideration.
