### ISSUE TITLE
No way to return to all people from group view in People module

### ISSUE THREAD

**Issue by dokterbob** [ONLYOFFICE/CommunityServer#149]

**Comment by andreysavihin** [comment]
Hello @dokterbob Please clear the filter or click to root item (Groups) of navigation menu.

**Comment by dokterbob** [comment]
@andreysavihin Thanks for the super quick reply. I think this is a UX issue; I've had to search for this to no avail for more time than it took me to file this issue, which means that the UI could me more obvious about this.

What do you reckon?

**Comment by Medanna** [comment]
Hello @dokterbob. Thanks for your opinion. We are already in progress with some changes in the UI/UX and will take this issue into consideration.
