### ISSUE TITLE
Develop a new module/feature to extend onlyoffice and compile for linux

### ISSUE THREAD

**Issue by mahermeg17** [ONLYOFFICE/CommunityServer#15]
Hi,
Great product. But I need to develop some specific module for my own use. And add it to the main menu like calendar and CRM.
How to proceed ? developing with visual studio ? how to add the new module to the project and compile all for a linux system ?
thanks in advance.

**Comment by AnaMih** [comment]
You can download source files from http://sourceforge.net/projects/teamlab/files/
There is a Build.sh script-file in the "build" folder.

**Comment by mahermeg17** [comment]
OK I will try to build it.
And for the IDE is it better to use VS 2012 or a mono IDE like www.monodevelop.com ?
witch one ONLYOFFICE dev team are using ?

**Comment by AnaMih** [comment]
It's better to use VS.

**Comment by mahermeg17** [comment]
thank you
