### ISSUE TITLE
Enabling SSL prevents connect to document server

### ISSUE THREAD

**Issue by githublti** [ONLYOFFICE/CommunityServer#151]
First my setup

Two virtual machines on the DMZ
Both running Debian 9
Installing using apt following onlyoffice.helpcenter website
Running internal DNS
Community Server: 9.6.5.771 via apt
Document Server: 5.2.8-24 via apt
Mono version: 5.18.1.3 via apt

Following the instructions for both the Document server and Community server went well enough.  Configuring the Community server to connect to the Document server also worked fine.  

![image](https://user-images.githubusercontent.com/38698996/55959540-f9c6f380-5c38-11e9-9fbb-98b2ebaa39fe.png)

I was able to create, open and modify Documents.  The problem occurs when I try to enable SSL (LetsEncrypt) on the Community server; it won't let me change the last entry on the settings panel.

Browser has confirmed a valid SSL Certificate, using curl to test the HTTPS URL also confirms a valid SSL cert.  But, trying to update the "Community Server address for requests from the Document Service" fields fails with

![image](https://user-images.githubusercontent.com/38698996/55959434-c7b59180-5c38-11e9-9e88-994f7a0dea7f.png)

Any suggestions on diagnosis would be appreciated,

Doug

**Comment by LinneyS** [comment]
Can you open the next link in your browser:
`http://oodocserver.****.info/web-apps/apps/api/documents/api.js`

**Comment by githublti** [comment]
Yes, 

From Firefox on the local network and with Curl on the DMZ.  A portion is pasted below:

/**
 * Copyright (c) Ascensio System SIA 2013. All rights reserved
 *
 * http://www.onlyoffice.com
 */

I've also noted when trying to connect from the Document server to the Community Server with curl 

curl https://onlyoffice.*****.info

I get:

```
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="/auth.aspx">here</a></h2>
</body><html>

```

Doug

**Comment by LinneyS** [comment]
Try the address
`http://oodocserver.****.info/ds-vpath`

**Comment by githublti** [comment]
I get from a browser (Firefox)

Cannot GET /ds-vpath

Doug

**Comment by ibnpetr** [comment]
@githublti 
Please enable HTTPS on the DocumentServer, 
The point is that your Community Server (HTTPS) doesn't allow you to use Document Server (HTTP) due to the [mixed content policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content)

**Comment by githublti** [comment]
That fixed the issue, thanks!

Doug

**Comment by L-u1** [comment]
Hi 

I have the same issue, have newly installed ONLYOFFICE_Workspace_Win 24.12, changed settings in Control panel to
```
Document editing addr: ds-vpath
Document service addr for req. from Community server: https://myserver.local:8083/
Community server addr for req. from Document server: https://myserver.local/
```
and copied ds-ssl.conf.tmpl to ds.conf (added my crt & key into),
so ds.conf  now looks as shown below.

But now I can open only https://myserver.local/welcome
Trying to open smth like https://myserver.local/controlpanel/backup Control Panel says:
Cannot GET /controlpanel/backup

Or Cannot GET /ds-vpath as from @githublti 

What have I missed and what have to be done? 

Thank you.

```
include includes/http-common.conf;

## Normal HTTP host
server {
  listen 0.0.0.0:80;
  listen [::]:80 default_server;
  server_name _;
  server_tokens off;
  set $secure_link_secret e8mymMnNsALzrBYfbIt2;

  ## Redirects all traffic to the HTTPS host
  root /nowhere; ## root doesn't have to be a valid path since we are redirecting
  rewrite ^ https://$host$request_uri? permanent;
}

#HTTP host for internal services
server {
  listen 127.0.0.1:80;
  listen [::1]:80;
  server_name localhost;
  server_tokens off;
  set $secure_link_secret e8mymMnNsALzrBYfbIt2;
  
  include includes/ds-common.conf;
  include includes/ds-docservice.conf;
}

## HTTPS host
server {
  listen 0.0.0.0:443 ssl;
  listen [::]:443 ssl default_server;
  server_tokens off;
  set $secure_link_secret e8mymMnNsALzrBYfbIt2;
  root /usr/share/nginx/html;

  ## Strong SSL Security
  ## https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
  ssl_certificate "C:\\Program Files (x86)\\Ascensio System SIA\\DocumentServer\\nginx\\certificates\\local.cer";
  ssl_certificate_key "C:\\Program Files (x86)\\Ascensio System SIA\\DocumentServer\\nginx\\certificates\\local.key";
  # Uncomment string below and specify the path to the file with the password if you use encrypted certificate key
  # ssl_password_file {{SSL_PASSWORD_PATH}};
  ssl_verify_client off;

  ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";

  ssl_protocols TLSv1.2;
  ssl_session_cache  builtin:1000  shared:SSL:10m;

  ssl_prefer_server_ciphers   on;

  add_header Strict-Transport-Security max-age=31536000;
  # add_header X-Frame-Options SAMEORIGIN;
  add_header X-Content-Type-Options nosniff;

  ## [Optional] If your certficate has OCSP, enable OCSP stapling to reduce the overhead and latency of running SSL.
  ## Replace with your ssl_trusted_certificate. For more info see:
  ## - https://medium.com/devops-programming/4445f4862461
  ## - https://www.ruby-forum.com/topic/4419319
  ## - https://www.digitalocean.com/community/tutorials/how-to-configure-ocsp-stapling-on-apache-and-nginx
  # ssl_stapling on;
  # ssl_stapling_verify on;
  # ssl_trusted_certificate /etc/nginx/ssl/stapling.trusted.crt;
  # resolver 208.67.222.222 208.67.222.220 valid=300s; # Can change to your DNS resolver if desired
  # resolver_timeout 10s;

  ## [Optional] Generate a stronger DHE parameter:
  ##   cd /etc/ssl/certs
  ##   sudo openssl dhparam -out dhparam.pem 4096
  ##
  # ssl_dhparam /etc/ssl/certs/dhparam.pem;

  include includes/ds-*.conf;

}

```
