### ISSUE TITLE
Document-Server using Postgres, Community-Server using MySQL!?

### ISSUE THREAD

**Issue by m4k5ym** [ONLYOFFICE/CommunityServer#153]
Hello,

I was about to install community server and document server on same system.

I just don't understand one thing. Why is document server using postgres and community mysql?

The problem I may become with that solution is that I have to maintain two different systems and databases for one solution and this makes literally no sense at all.

Is there a plan to resolve this issue in long term view?

Best Regards,
Maksym

**Comment by dealproc** [comment]
I have been thinking about creating/providing a PR to support Postgres for Community Server.  If the repo owners would take a PR for this, let me know.

**Comment by m4k5ym** [comment]
No reply by repo owners.

Bye Bye issue
