### ISSUE TITLE
Does the mail aggregator support Microsoft Exchange 2010, 2013

### ISSUE THREAD

**Issue by mahermeg17** [ONLYOFFICE/CommunityServer#16]
Hi,

Does the mail aggregator support Microsoft Exchange 2010, 2013 ?

Best regards,

**Comment by AnaMih** [comment]
Mail aggregator works with Ms Exchange 2010 in OnlyOffice Community 8.6.2 version and later.

**Comment by mahermeg17** [comment]
but it's only code source of OnlyOffice 8.5.1 published.
when the 8.6.2 version will be published ?
Or at least can you give some notes for developers to support M.Ex 2010 and 2013 ?

**Comment by AnaMih** [comment]
8.6.2 version is already supports Ms Exchange 2010. It will be published as soon as possible.

**Comment by mahermeg17** [comment]
Test with an Exchange 2013 account works fine.
we should just configure the right IMAP/SMPT config
;)

**Comment by mahermeg17** [comment]
configuring onlyoffice mail aggregator with a hosted exchange 2013 account by OVH, works fine: sending and receiing mail.
But the sent mail from onlyoffice are not showed into the SENT folder in the main Exchange account even the mail are correctly recived.

**Comment by mahermeg17** [comment]
Hi again,

when checking the web.api.log file I found that it Cannot find Sent folder over Imap.
For exchange, it should use smtp for send items.
And into the CommunityServer-master\module\ASC.Api\ASC.Api.Mail\MailSendQueue.cs, there is only a StoreMessageToImapSentFolder implemented.

     ASC.Api.Mail.MailApi.GetContacts(String term) at \CommunityServer-master\module\ASC.Api\ASC.Api.Mail\MailApi.Contacts.cs:ligne 52
    2015-09-22 04:07:37,510 ERROR [6] ASC.Api - StoreMessageToSentFolder() in MailboxId=1 failed with exception:
    System.IO.InvalidDataException: Cannot find Sent folder over Imap. MailboxId=1 
       à ASC.Api.Mail.MailSendQueue.StoreMessageToImapSentFolder(MailBox mbox, Message mimeMessage)

**Comment by AnaMih** [comment]
The error "Cannot find Sent folder over Imap." means that onlyoffice mail can't find the folder with the name "Send". 
In the database it is necessary to complete the request
INSERT INTO `mail_imap_special_mailbox` (`server`, `name`, `folder_id`, `skip`) VALUES ('{your-exchange-domain}', '{sent folder name}', 2, 0);
Where "your-exchange-domain" - your ms Exchange server domain name, "sent folder name" - your folder with outgoing mail.

**Comment by mahermeg17** [comment]
THANK YOU.
