### ISSUE TITLE
Broken dependecies and more...

### ISSUE THREAD

**Issue by m4k5ym** [ONLYOFFICE/CommunityServer#163]
Hello,

After my adventure of installing ONLYOFFICE CommunityServer on CentOS 7 I'm really disappointed.

Your install instruction on https://helpcenter.onlyoffice.com/server/linux/community/linux-installation-centos.aspx is absolute useless. There are not all dependencies documented, some package decisions doesn't make any sense. Literally. Why the hell I should use official Oracle "community" software? MariaDB is absolute fine with CentOS and delivered with epel / scl repository. On documentserver nginx is requried with minimum version and communityserver seems not to care about it!?

You guys really have to do some clean up job both on your software and documentation. I already opened an issue because of the fact that different database types are used for "one plattform". Move everything to postgresql or mysql not both.

In general your documentation isn't really good. After reading most pages I still have alot of question marks open. I'm really wondered how many basic user a able to install your "opensource software" on their own.

Sincerly

**Comment by alexanderonlyoffice** [comment]
Hello @m4k5ym, thank you for your feedback. The guides require improvements. We will try to update all the documentation in the nearest future.
