### ISSUE TITLE
Deploy Community Server on linux

### ISSUE THREAD

**Issue by saidiahd** [ONLYOFFICE/CommunityServer#17]
Hi, i have compiled OnlyOffice CommunityServer by running the shell script BuildAndDeploy.sh. The Build succeeded with 0 for both error and warning. But when a trying to access my VM , i only found the "Welcome to nginx!" page. So i am asking is there any other step to do in order make it run? and is there any other deployment process to do ? 
thanks for helping.

**Comment by AnaMih** [comment]
Please, configure the file /etc/nginx/sites-available/onlyoffice.config, 80 port should be set to OnlyOffice Community Server.
