### ISSUE TITLE
Wrong `unread` state in mail client

### ISSUE THREAD

**Issue by vegansk** [ONLYOFFICE/CommunityServer#174]
I am using filters that moves emails into specific folders. And periodically I run into this situation when there is no unread messages in the list, but they are in the tree and filter shows already read messages.

![image](https://user-images.githubusercontent.com/2908508/64833512-7c991380-d608-11e9-809f-848690cbcd46.png)

Workaround: create new folder, move **all** the messages to it, delete old folder, rename new folder, fix filters. If I move only messages that listed as unread, list becomes empty, but the tree doesn't updates:

![image](https://user-images.githubusercontent.com/2908508/64834188-11047580-d60b-11e9-9c4e-0cada35a40d4.png)

**Comment by HelenBelova17** [comment]
Hello, @**vegansk**, this is a bug, issue 34937 in our internal issue tracker.
You can fix it manually, follow this link http://example.com/api/2.0/mail/folders/recalculate.json where http://example.com is replaced with the address of your portal. You can see the status of the operation https://example.com/api/2.0/mail/operations .

**Comment by vegansk** [comment]
Thanks, it worked.
