### ISSUE TITLE
Application Exception - Runtime Error

### ISSUE THREAD

**Issue by agisofttm** [ONLYOFFICE/CommunityServer#175]
Sorry but, i'm almost finish with my ideas, how to fix this....

I've have Ubuntu 16.04 installation via last script (no Docker and no Mail Server), install run smoothly, everything's ok with setup with web interface, but after rebooting of system I have this error :

Application Exception
Runtime Error
A runtime error has occurred

Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed (for security reasons).

and this is only after Restart of machine.... please give me some advise or some points to repair this

**Comment by Carazyda** [comment]
Hello @agisofttm I think your mysql server didn't start after reboot, please check status of this service. And you can look at the logs (/var/log/onlyoffice/web.log).

**Comment by agisofttm** [comment]
Hello @Carazyda, 

Thanks for the points. Everything run smooth now, except OCR Plugin in Document server, but everything is fine. Thanks again.
