### ISSUE TITLE
Cannot be install on Windows 10 x64

### ISSUE THREAD

**Issue by ImJezze** [ONLYOFFICE/CommunityServer#176]
ONLYOFFICE_CommunityServer_Win-install.v10.0.715.exe

![grafik](https://user-images.githubusercontent.com/11963815/65385055-1d36b400-dd2a-11e9-89a2-c359099affa8.png)

OS: Windows 10 x64 Pro
Version: 10.0.18362

Which versions of Windows are supported?

**Comment by Carazyda** [comment]
Hello @ImJezze We support only server versions of windows - https://helpcenter.onlyoffice.com/server/windows/community/system-requirements.aspx.
