### ISSUE TITLE
onlyoffice document server windws 7

### ISSUE THREAD

**Issue by idbricco** [ONLYOFFICE/CommunityServer#18]
i have installed new vm with  windows 7 and i tried to install documentserver 3.0.
All required software are ok.
when install document server , installation fail on status server and interrupt installation.
I tried on windows 8 and 10 and same rusult.
do you ave any idea?
thaks

**Comment by idbricco** [comment]
update: tried with clean  w2008 server , same error.

**Comment by AnaMih** [comment]
1) Document Server 3.0 can be installed on windows8/server2012 and later.
2) About Win 8 and 10: 
- please, send us the screenshots of the error during installation?
- are all the prerequisites installed? (http://helpcenter.onlyoffice.com/server/windows/document/install-office-apps.aspx)

**Comment by idbricco** [comment]
thanks for your replay.
yes  prerequisites are ok.
i tried also win 2008 server but same result.
w2008 server are supported or i need windows 2012?

**Comment by AnaMih** [comment]
Yes, please, use win server 2012 for Document Server version 3.0.

**Comment by idbricco** [comment]
thaks for your support!
