### ISSUE TITLE
Document files more than 100 MB doesn't open

### ISSUE THREAD

**Issue by StasStryukov91** [ONLYOFFICE/CommunityServer#183]
Good day.
We have a problem with our cummnuty server.
We've uploaded ppt file  185MB at server. But when we try to open it, there is an error
https://ibb.co/0rJ5Ck9

All files, like doc,xls,ppt,pdf can't be opened and can't be downloaded form the server. When we send external link to our clients, they can't download documents more 100 Mb.

How to solve the problem?

**Comment by LinneyS** [comment]
Todo: 
move the size to configuration
https://github.com/ONLYOFFICE/CommunityServer/blob/56d5135106180f78047d01c823a5b9bb77246257/web/studio/ASC.Web.Studio/Core/SetupInfo.cs#L109-L112

**Comment by StasStryukov91** [comment]
> Todo:
> move the size to configuration
> https://github.com/ONLYOFFICE/CommunityServer/blob/56d5135106180f78047d01c823a5b9bb77246257/web/studio/ASC.Web.Studio/Core/SetupInfo.cs#L109-L112

I'm sorry, but where can i find this file? 
There is no file "SetupInfo.cs" in community docker container.

**Comment by StasStryukov91** [comment]
> Todo:
> move the size to configuration
> https://github.com/ONLYOFFICE/CommunityServer/blob/56d5135106180f78047d01c823a5b9bb77246257/web/studio/ASC.Web.Studio/Core/SetupInfo.cs#L109-L112

As I understand it, this functionality can be added in the next version, but it will not be soon?

**Comment by StasStryukov91** [comment]
Omg, a little enchantment, but so long to wait.

So, if we buy your product, this problem can be solved faster? 

Or just make the link for files more 100 mb donwloadable without editing like in mail.ru cloud or google drive.

**Comment by Carazyda** [comment]
Hello @StasStryukov91 we will fix this in the next release, which will be soon.

**Comment by LinneyS** [comment]
https://github.com/ONLYOFFICE/CommunityServer/blob/43debc5e01567a1d21a8af19dfb74bf2befa3a02/web/studio/ASC.Web.Studio/Core/SetupInfo.cs#L396

Now you can add `web.available-file-size` to `web/studio/ASC.Web.Studio/web.appsettings.config` config.

**Comment by StasStryukov91** [comment]
Thanks, it's works now :)

**Comment by zapzqc** [comment]
@LinneyS 
I have already add the settings
`<add key="web.available-file-size" value="1000000000" />`
when I open the document，it shows download error. How to fix it？
![QQ截图20200413171623](https://user-images.githubusercontent.com/3996569/79109229-88b99f00-7daa-11ea-80ec-bfdbef80ef5b.png)

**Comment by zapzqc** [comment]
修改E:\Program Files (x86)\Ascensio System SIA\CommunityServer\WebStudio 下的 web.appsettings.config 中 添加：
<add key="web.available-file-size" value="1000000000" />
修改E:\Program Files (x86)\Ascensio System SIA\DocumentServer\config\default.json中的：
"FileConverter": {
		"converter": {
			"maxDownloadBytes": 1048576000,       // 这里加了个0
			"downloadTimeout": {
				"connectionAndInactivity": "20s",       // 这里改成了20s 
				"wholeCycle": "2m"
			},
			"downloadAttemptMaxCount": 3,

**Comment by xandre31** [comment]
Hello,

I do have the same issue and even after having change value of "maxDownloadBytes" in /etc/onlyoffice/documentserver/default.json, I still have same error "file larger than 100mb will not be edited".

Could anyone help me to fix it please ?

Thanks.
Regards,

**Comment by Carazyda** [comment]
Hello @xandre31 did you add this key to WebStudio/web.appsettings.config ?

> <add key="web.available-file-size" value="1000000000" />

After that you need to restart `systemctl restart monoserve`.

**Comment by xandre31** [comment]
Hello @Carazyda,  I missed it and only changed values in /etc/onlyoffice/documentserver/default.json on document server.
I just add <add key="web.available-file-size" value="1500000000" /> in /var/www/onlyoffice/WebStudio/web.appsettings.config on onlyoffice server and now I can open file larger thant 100Mb. 

thank you very much for your quick and kind help !
