### ISSUE TITLE
The ONLYOFFICE Community Edition Setup Wizard ended prematurely

### ISSUE THREAD

**Issue by pc-v2** [ONLYOFFICE/CommunityServer#186]
![image](https://user-images.githubusercontent.com/58063311/70690997-9242d580-1cea-11ea-9048-b8217a87b840.png)

`

**Comment by pc-v2** [comment]
[log, zip file, txt inside](https://app.box.com/s/o4qima1r279kz16gqqlb6fi9qti7t9cm)

**Comment by Carazyda** [comment]
Hello @pc-v2 Please specify which version of Windows Server you are using? And try to install onlyoffice on a clean OS.

**Comment by pc-v2** [comment]
i think i download the wrong version
