### ISSUE TITLE
Mail Module : Auto reply feature

### ISSUE THREAD

**Issue by mahermeg17** [ONLYOFFICE/CommunityServer#19]
Hi,
Does the mail module can configure an autoreply feature ? Even the source code of the mail autoreply exist under CommunityServer/module/ASC.Mail/ASC.Mail.Autoreply

**Comment by AnaMih** [comment]
Unfortunately, mail module cannot  configure an autoreply feature.

**Comment by mahermeg17** [comment]
so what about the existing code source ?

**Comment by AnaMih** [comment]
Existing source code may be used for adding the comments from email.
