### ISSUE TITLE
Custom Module development - How to disable bundling and minification while developing.

### ISSUE THREAD

**Issue by dealproc** [ONLYOFFICE/CommunityServer#193]
I am working on a custom module, and it seems to be that I must use the code-behind to include javascript and css files into the page(s) properly.  The issue with this is that I have to constantly adjust how these files are created to get updated javascript/styles into the browser.

I'm also reviewing a few app settings, and there are a few properties that _seem to be_ relevant to this need, but none make much sense.

Can guidance be provided on how to disable the bundling & minification until a release build is ready?

**Comment by andreysavihin** [comment]
Hello @dealproc ! Check this https://github.com/ONLYOFFICE/CommunityServer/blob/master/web/studio/ASC.Web.Studio/web.appsettings.config#L54

**Comment by dealproc** [comment]
This is what I wound up having.  I believe I had to shut-down the client cache as well as the client bundling to get where I needed to be.

```xml
  <key="web.client.cache" value="false" />
  <add key="web.client.bundling" value="false" />
  <add key="web.client.cache.resetkey" value="20171012" />
  <add key="web.client.store" value="true" />
```
