### ISSUE TITLE
what is the teamlab connectionString for?

### ISSUE THREAD

**Issue by mahermeg17** [ONLYOFFICE/CommunityServer#20]
hi,
in the web\studio\ASC.Web.Studio\web.connections.config and other files we found a teamlab connectionString. what is it for ? does onlyoffice connect to a remote server even it's for a local use ?

    <?xml version="1.0" encoding="utf-8"?>
    <connectionStrings>
     <clear />
      <add name="default" connectionString="Server=localhost;Database=onlyoffice;User ID=root;Password=onlyoffice;Pooling=True;Character Set=utf8;AutoEnlist=false" providerName="MySql.Data.MySqlClient" />
      <add name="teamlabsite" connectionString="Server=teamlab;Database=teamlab_site;User ID=dev;Password=dev;Pooling=true;Character Set=utf8;AutoEnlist=false" providerName="MySql.Data.MySqlClient" />
    </connectionStrings>

**Comment by AnaMih** [comment]
Teamlab connectionString in web.connections.config remained identical to that of the old version. It isn't being used now in the current version of onlyoffice. Some other files haven't been updated after rebranding and still may content the name "teamlab".

**Comment by mahermeg17** [comment]
OK. Thank you.
