### ISSUE TITLE
Documentation for controls within Web UI

### ISSUE THREAD

**Issue by dealproc** [ONLYOFFICE/CommunityServer#201]
I'm authoring a plugin/add-in to OnlyOffice, and am trying to keep the styles 100% with the base system.  In doing so, I am trying to use as much of the front-end UI tools that are used within the site, inclusive of dialogs, etc.

Is there deeper documentation available to better understand the method(s) to build each of the UI elements so that I am not manually reading many JavaScript files and determining this on my own?  I can do so, but am burning a lot of time.

**Comment by Carazyda** [comment]
Hello @dealproc Sorry, but we don't have detailed documentation, except api.onlyoffice.com.

In new generation of communityserver, we will have a storybook, that include all documentation about it.

**Comment by dealproc** [comment]
Ok, thank you.

I was hoping for a short-cut method for this, but will continue the grueling task of extracting the capabilities by spelunking the existing UI code.
