### ISSUE TITLE
'System.InvalidOperationException' occurred in System.ServiceModel.dll

### ISSUE THREAD

**Issue by mahermeg17** [ONLYOFFICE/CommunityServer#21]
Hi,

I got this error while runing from VS 2013.

    A first chance exception of type 'System.InvalidOperationException' occurred in System.ServiceModel.dll

it belongs to this part of code in CommunityServer-master\common\ASC.Core.Common\Billing\TariffService.cs

    private BillingClient GetBillingClient()
        {
            try
            {
                return new BillingClient(test);
            }
            catch (InvalidOperationException ioe)
            {
                throw new BillingNotConfiguredException(ioe.Message, ioe);
            }
            catch (ReflectionTypeLoadException rtle)
            {
                log.ErrorFormat("{0}{1}LoaderExceptions: {2}",
                    rtle,
                    Environment.NewLine,
                    string.Join(Environment.NewLine, rtle.LoaderExceptions.Select(e => e.ToString())));
                throw;
            }
        }

the fullstack issue:
Documents\DKTech\CommunityServer-master\common\ASC.Core.Common\Billing\TariffService.cs:ligne 399
  InnerException: System.InvalidOperationException
       HResult=-2146233079
       Message=Impossible de trouver un élément de point de terminaison par défaut qui fait référence au contrat 'ASC.Core.Billing.IService' dans la section de configuration du client ServiceModel. Ceci peut être dû au fait que le fichier de configuration de votre application est introuvable ou que l'élément de point de terminaison correspondant à ce contrat est introuvable dans l'élément client.
       Source=System.ServiceModel
       StackTrace:
            à System.ServiceModel.Description.ConfigLoader.LoadChannelBehaviors(ServiceEndpoint serviceEndpoint, String configurationName)
            à System.ServiceModel.ChannelFactory.ApplyConfiguration(String configurationName, Configuration configuration)
            à System.ServiceModel.ChannelFactory.ApplyConfiguration(String configurationName)
            à System.ServiceModel.ChannelFactory.InitializeEndpoint(String configurationName, EndpointAddress address)
            à System.ServiceModel.ChannelFactory`1..ctor(String endpointConfigurationName, EndpointAddress remoteAddress)
            à System.ServiceModel.ConfigurationEndpointTrait`1.CreateSimplexFactory()
            à System.ServiceModel.ConfigurationEndpointTrait`1.CreateChannelFactory()
            à System.ServiceModel.ClientBase`1.CreateChannelFactoryRef(EndpointTrait`1 endpointTrait)
            à System.ServiceModel.ClientBase`1.InitializeChannelFactoryRef()
            à System.ServiceModel.ClientBase`1..ctor()
            à ASC.Core.Billing.BillingClient..ctor(Boolean test) dans c:\Users\MegaDev\My Documents\DKTech\CommunityServer-master\common\ASC.Core.Common\Billing\BillingClient.cs:ligne 51
            à ASC.Core.Billing.TariffService.GetBillingClient() dans c:\Users\MegaDev\My Documents\DKTech\CommunityServer-master\common\ASC.Core.Common\Billing\TariffService.cs:ligne 395
       InnerException:

**Comment by mahermeg17** [comment]
Hi,
And I also found a strange code into common\ASC.Core.Common\Configuration\AmiPublicDnsSyncService.cs
and what is this url http://169.254.169.254/latest/meta-data/public-hostname ??

     private static string GetAmiPublicDnsName()
        {
            try
            {
                var request = WebRequest.Create("http://169.254.169.254/latest/meta-data/public-hostname");
                request.Timeout = 5000;
                using (var responce = request.GetResponse())
                using (var stream = responce.GetResponseStream())
                using (var reader = new StreamReader(stream))
                {
                    return reader.ReadToEnd();
                }
            }
            catch (WebException ex)
            {
                if (ex.Status == WebExceptionStatus.ProtocolError)
                {
                    throw;
                }
            }
            return null;
        }

**Comment by AnaMih** [comment]
This is code from saas onlyoffice version. You may delete it if you'd like.

**Comment by mahermeg17** [comment]
should I delete all the module common\ASC.Core.Common\Billing ?

**Comment by AnaMih** [comment]
Yes, you may delete it.
