### ISSUE TITLE
After upgrading CommunityServer from  9.6.5.239  to 10.5

### ISSUE THREAD

**Issue by BololZ** [ONLYOFFICE/CommunityServer#210]
Hello,

After upgrade, i can't connect to Web interface with error HTTP 500. I use Centos 7 and all prerequisite.

I found an error in 
> /var/log/onlyoffice/svcIndex.log
 :
`ERROR [37] ASC.Indexer - Ping false MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts. ---> System.InvalidOperationException: Sequence contains more than one matching element`

It seems a configuration error but i didn't found it.

Thanks.

**Comment by BololZ** [comment]
Hello,

I found the issue with the config file : 
> /var/www/onlyoffice/WebStudio/web.connections.config

I used _web.connections.config.rpmnew_ and configure it.

**Comment by Xandersoft** [comment]
> Hello,
> 
> I found the issue with the config file :
> 
> > /var/www/onlyoffice/WebStudio/web.connections.config
> 
> I used _web.connections.config.rpmnew_ and configure it.

Yes, thanks for idea.
* update from 10.0.1 to 10.5
* CentOS 7

## Error:
on WebPage 
  * Http 500  error (500 Internal Server Error)
  * Application Exception
  * Runtime Error

## on Logs:
`/var/log/onlyoffice/web.log`:

* 'Unable to connect to any of the specified MySQL hosts'
* `/var/log/onlyoffice/web.sql.log `
```
2020-xx-xx 20:01:46,986|5|0.8865|Connection.Open||
2020-xx-xx 20:01:46,986|5|0.6844|Connection.Open||
2020-xx-xx 20:01:47,308|5|0.7029|Connection.Open||
2020-xx-xx 20:01:47,308|5|0.6393|Connection.Open||
2020-xx-xx 20:01:47,311|5|0.7766|Connection.Open||
2020-xx-xx 20:01:47,311|5|0.7086|Connection.Open||
2020-xx-xx 20:01:47,317|5|0.7081|Connection.Open||
2020-xx-xx 20:01:47,319|5|0.8018|Connection.Open||
2020-xx-xx 20:01:47,319|5|0.7317|Connection.Open||
2020-xx-xx 20:01:47,323|5|0.8105|Connection.Open||
2020-xx-xx 20:01:47,411|54|0.9355|Connection.Open||
2020-xx-xx 20:01:47,411|5|1.0967|Connection.Open||
2020-xx-xx 20:01:47,425|55|0.7872|Connection.Open||
2020-xx-xx 20:01:47,428|5|0.564|Connection.Dispose||
2020-xx-xx 20:01:52,665|26|1.4647|Connection.Open||
2020-xx-xx 20:01:52,665|26|0.0032|Connection.Dispose||
```

# Solution
`/var/www/onlyoffice/WebStudio/web.connections.config`

> replace `localhost` with `127.0.0.1`
