### ISSUE TITLE
OnlyOffice Community setup wizard ended prematurely on Win 10

### ISSUE THREAD

**Issue by admin-pcngroup** [ONLYOFFICE/CommunityServer#214]
Hello all,
I was trying to install Onlyoffice community server on my Windows 10 machine but after having met all the prerequisites, the setup doesn't go on and _ends prematurely_ after approx. 1 h of installing.
I attach my log file to this message.

What should I do?
Thank you to all. 
All the very best

**Comment by Carazyda** [comment]
Onlyoffice Community Server doesn't support Win 10, only server versions of Windows.
