### ISSUE TITLE
Link in readme redirect on 404

### ISSUE THREAD

**Issue by jfustier** [ONLYOFFICE/CommunityServer#216]
Link redirect on 404.

![readme_link](https://user-images.githubusercontent.com/50904366/77307733-19e0ad00-6cfa-11ea-9042-deca7c40f156.png)

**Comment by andreysavihin** [comment]
Hi @jfustier ! Thank you for your comment. We forgot to fix readme. The repository has been deleted. All instructions are transferred to the current repository. Pay attention to projects  [ASC.Web.Sample](https://github.com/ONLYOFFICE/CommunityServer/tree/master/web/studio/ASC.Web.Studio/Products/Sample), [ASC.Api.Sample](https://github.com/ONLYOFFICE/CommunityServer/tree/master/module/ASC.Api/ASC.Api.Sample)
