### ISSUE TITLE
Edits and changes made in Onlyoffice are not saved into Nextcloud and are lost

### ISSUE THREAD

**Issue by timo12357** [ONLYOFFICE/CommunityServer#217]
####Issue
Edits and changes made in Onlyoffice are not saved into Nextcloud and sync from Nextcloud to Onlyoffice destroys all changes made in Onlyoffice.

#### Expected Behavior
Edits and changes written in Onlyoffice sync to the local desktop environment and the changes done in the desktop environment sync to OnlyOffice

#### Actual Behavior
Files stored in the local desktop environment are synced flawlessly to Nextcloud. Onlyoffice opens them flawlessly and lets the user edit the document. After saving the document and or logging out from nextcloud changes are kept in OnlyOffice cache and never written to the actual document. When user opens same document from the desktop the changes have disappeared. If user saves the document with a small change, this change is synced to OnlyOffice overwriting the changes in the cache.

#### Possible Fix
Write cache data to file regularly and frequently. Recognize when user leaves Onlyoffice or closes file and write cache to file. In short: Copy the functionality of Google Docs.

#### Steps to Reproduce

1. Use a desktop wordprocessor and create a document in a NextCloud synced folder in your desktop environment 
2. Log onto the Nextcloud web UI and open the file with OnlyOffice.
3. Ask colleague to do the same
4. Make changes in document
5. Exit document 
6. Open document with desktop wordprocessor from local NextCloud synced folder.
7. Notice that the changes never were saved to the file in NextCloud,.
8. Open file in OnlyOffice from the Nextcloud web UI to notice changes are still there
9. Close OnlyOffice
10. Make minimal change in the desktop wordprocessor and save file locally.
11. Let NextCloud sync
12. Open file in OnlyOffice from the Nextcloud web UI to notice all changes made in OnlyOffice have been lost and overwritten with those made in the desktop environment
13. Feel despair.

#### Context
We just lost 2 days worth of expensive work made by our consultant. This is becoming very expensive to us!

#### Your Environment

* Nextcloud 18.0.3
* OnlyOffice Community Server bundled with NextCloud 18
* Nextcloud desktop client 2.6.4 Linux
* Nextcloud desktop client 2.6.4 Mac

**Comment by alexanderonlyoffice** [comment]
@timo12357, please note that if you are using Community Document Server integrated in Nextcloud Hub, you need to contact Nextcloud Support Team in case any issues are encountered, as this application was developed by Nextcloud Team. Please refer to this post on our [Forum](https://dev.onlyoffice.org/viewtopic.php?f=53&t=25444).
