### ISSUE TITLE
install-Debian.sh fails with ModuleNotFoundError: No module named 'setuptools'

### ISSUE THREAD

**Issue by gr4ssi** [ONLYOFFICE/CommunityServer#219]
I tried to install the debian version with install-Debian.sh on a fresh Debian 10.
After a while, the installer crashes with the following message:

_Collecting radicale
  Downloading Radicale-2.1.11.tar.gz (76 kB)
     |████████████████████████████████| 76 kB 3.8 MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hnpaljli/radicale/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hnpaljli/radicale/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-hnpaljli/radicale/pip-egg-info
         cwd: /tmp/pip-install-hnpaljli/radicale/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    **ModuleNotFoundError: No module named 'setuptools'**
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output._

I tried to fix it by installing python-setuptools:
> apt-get install python-setuptools

After that, it still didn't work.

What finally fixed it:

> **pip install -U pip setuptools**

I then triggered the install again and it finished without errors.

I did call install-Debian.sh directly, without the wrapper, but I don't think this is the root cause of the issue.

**Comment by Carazyda** [comment]
Hello @gr4ssi I cant reproduce your problem on a default installation of Debian 10.3. We cant predict all situations on os, if some system utils are not installed. Have you resolved your case and installed onlyoffice?

**Comment by gr4ssi** [comment]
Yes thanks, I got it to run finally. Wanted to include it into Nextcloud and needed to tweak some json-file to get it to talk to Nextcloud. But now it works. Thanks.
