### ISSUE TITLE
mail not delete from server (pop3)

### ISSUE THREAD

**Issue by idbricco** [ONLYOFFICE/CommunityServer#22]
I'am testing mail function.
I configured pop3 account and it is all ok.
only one big problem .... mail does not deleted from pop3 server.
is it correct or there some file or setting that can i editing to do it?
thanks and sorry form my english

**Comment by AnaMih** [comment]
It is correct. You can't delete emails from mail server through Mail module.

**Comment by kamuzon** [comment]
Why don't you do it? It will be very usefull.

**Comment by kamuzon** [comment]
IMAP is great solution. Thank you. But I need something else. IMAP leaves messages on server. I don't want to leave messages on mail server. I need to download them to "client". BTW to Onlyoffice portal. Then I don't download them - the mailbox increase on mail server. And free space is gone.
