### ISSUE TITLE
"Attach files from document" in email doesn't work while connected to Nextcloud via WebDAV

### ISSUE THREAD

**Issue by gr4ssi** [ONLYOFFICE/CommunityServer#220]
I've connected to my Nextcloud 18.0.3 via WebDAV, and in the documents section, I can see my WebDAV folder at the top, then some demo-documents, and a self created document.
Like this:
![grafik](https://user-images.githubusercontent.com/19840345/78150844-1eaf0a80-7438-11ea-89a5-b0354b017bff.png)

Now I configured email via imap, and try to add a file from the documents section by pressing "Attach files from document". 
What happens is, I briefly see a pop up with the onlyoffice logo but after a quarter of a second, it's gone again.
Here is a screenshot:
![grafik](https://user-images.githubusercontent.com/19840345/78150727-f9220100-7437-11ea-92e6-db058829e336.png)

Disconnecting WebDAV Nextcloud doesn't help, same result. I just checked to make sure.
Any idea how to fix this?
My OnlyOffice is Version 10.5.2.1048 on Debian 10 with docker.

**Comment by gr4ssi** [comment]
Disconnecting WebDAV Nextcloud doesn't help, same result. I just checked to make sure.

**Comment by Carazyda** [comment]
Hello @gr4ssi Please check error in the browser console and web.log, web.files.log, web.api.log.

**Comment by gr4ssi** [comment]
hello @Carazyda , thanks for your quick reply.
This is in the console log (via F12 in FF (but same behaviour in IE):
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. filechoice.aspx

In the three files  web.log, web.files.log and web.api.log, when observing them via tail -f, nothing changes when I click the button. The last entry in those files is from 3 hrs ago, so probably irrelevant.

**Comment by gr4ssi** [comment]
From the company server with IE11, Chrome, FF via RDP, it works. Very strange. Hmpf. Not sure what's different, there.

**Comment by Carazyda** [comment]
Please also check the Network tab in the browser, what happens with the request when you click on "attach" button?

**Comment by gr4ssi** [comment]
Found it: I've installed Dragon Naturally Speaking which puts a browser extension in place for every one of my browsers. I now disabled all extensions and turned them back on one by one. As soon as I turn on the extension, it doesn't work anymore. That's actually the first time in six years that this happens, never had any issues with the plugin. (It's for voice controlling the PC/browser.)
