### ISSUE TITLE
Mail Aggregator Issue

### ISSUE THREAD

**Issue by MikeP1990** [ONLYOFFICE/CommunityServer#223]
Install Method - RPM Linux Install
Operating System - CentOS 7.5 64Bit

I've connected an account but it's not communicating properly with the external server.

For example, when I read an email on OnlyOffice, it's not marked as read on the external server.  The same applies for replied and deleted.

Any ideas?

**Comment by Carazyda** [comment]
Hello @ MikeP1990 At Onlyoffice, we use MailAggregator, which only downloads mail, and does not have full synchronization, like imap.

**Comment by MikeP1990** [comment]
If that is the case, why is IMAP an option when adding an account?

**Comment by Carazyda** [comment]
you mean imap-server? Because all popular email services work on imap protocol and servers. But this does not mean that the mail client has full synchronization.

**Comment by MikeP1990** [comment]
Then the IMAP option should be removed as it causes confusion, it's shown as IMAP but acts as POP.

**Comment by Carazyda** [comment]
You can download email from pop or imap protocol, that your mail service provides. Please read this [information](https://helpcenter.onlyoffice.com/tipstricks/Mail-Project.aspx)
