### ISSUE TITLE
Can't edit files

### ISSUE THREAD

**Issue by slaver666** [ONLYOFFICE/CommunityServer#224]
CentOS 7.7.1908, Nginx 1.16.1, OnlyOffice Community 10.5.2
Nextcloud 18.0.3 on another server with FreeBSD 12 and Nginx, OnlyOffice Nextcloud app 4.1.4
Everything worked fine before. Now I can't edit any files via Nextcloud app. The files open successfully but I can only see content but can't edit.

**Comment by slaver666** [comment]
I suppose the ticket should be closed. I discovered that OnlyOffice app for Nextcloud can't edit old formats (doc, xls) but can edit new docx, xlsx. Is it correct behavior?

**Comment by Carazyda** [comment]
Hello @slaver666 Yes, `doc` and `xls` need to be converted to `docx` or `xlsx` format for edit.
