### ISSUE TITLE
Document files more than 100 MB doesn't open

### ISSUE THREAD

**Issue by zapzqc** [ONLYOFFICE/CommunityServer#225]
I have already added the settings
`<add key="web.available-file-size" value="1000000000" />`
When I open the document，it shows download error. How to fix it？
![QQ截图20200413171623](https://user-images.githubusercontent.com/3996569/79109229-88b99f00-7daa-11ea-80ec-bfdbef80ef5b.png)
Files less then 100M can be opened.

**Comment by Carazyda** [comment]
Hello @zapzqc Please check document server logs for errors, and web.files.log in the community server.

**Comment by zapzqc** [comment]
web.files.log
`2020-04-16 01:39:04,545 ERROR [6] ASC.Files - StreamFile 
2020-04-16 01:40:32,580 ERROR [90] ASC.Files - StreamFile `

**Comment by Carazyda** [comment]
You need to configure one more parameter - in `/etc/onlyoffice/documentserver/default.json`change
`"FileConverter": {
                "converter": {
                        "maxDownloadBytes":`

But Onlyoffice is not suitable for working with large files, and this can cause any errors. Do it at your own risk.

**Comment by zapzqc** [comment]
OK. Thanks, it's works now :)

**Comment by zapzqc** [comment]
When I update Doucment Server from 5.4.2 to 5.5.1，I changed the default.json,it shows 
![image](https://user-images.githubusercontent.com/3996569/79534672-cd488180-80ad-11ea-9289-c802b2ad07a4.png)
