### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by ralgozino** [ONLYOFFICE/CommunityServer#23]
Hello! 

 First, let me thank you, onlypffice is a great piece of software! Sadly, the lack of LDAP support is stopping us from using it in a daily basis :(. Is there any chance of having LDAP login in the community server? We are testing the docker images.

Thanks!

**Comment by AnaMih** [comment]
LDAP is currently in the stage of testing.  It will be released in the next version of OnlyOffice.

**Comment by ralgozino** [comment]
Great news! We'll be waiting for it. Thanks!

**Comment by intlabs** [comment]
This is awesome, support for LDAP (389ds/FreeIPA here) would enable us to use OnlyOffice as well. Do you have an ETA for the next release? I'd be more than happy to help in any way I can.

Cheers

**Comment by AnaMih** [comment]
LDAP will be released in the Enterprise version (will be available next month).

**Comment by ralgozino** [comment]
@AnaMih by any chance will LDAP be available in the CommunityServer?

**Comment by AnaMih** [comment]
Unfortunately, Ldap is not included into the list of planned features of nearest releases.

**Comment by ychoucha** [comment]
Hello,

up this topic, because i m looking for ldap on CommunityServer ?

how add it please ?

**Comment by alexeybannov** [comment]
This functionality is available in the paid version of ONLYOFFICE Enterprise Edition. https://www.onlyoffice.com/enterprise-edition.aspx

**Comment by ychoucha** [comment]
only on the paid version :'(

can we acces in command line to add user and group ?

onlyoffice looks very cool, but we need to integrate it on my Windows system to make it all my user using it.

we need to sync exchange calendare mail task ...

can we make that with community editon ?

or i have to see other program ?

**Comment by alexeybannov** [comment]
Add users and groups, you can through our REST API. (https://api.onlyoffice.com). Yes, you can also write your own module. The sample module will be available soon.

**Comment by ychoucha** [comment]
yes i think with that 👍 
u can do something : 

https://api.onlyoffice.com/portals/section/group
