### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by pankajmalkani** [ONLYOFFICE/CommunityServer#235]
Hi Sir/Madam,
this is to notify you about the problems/issues we are facing the installation of our software portal along with onlyoffice portal using same SSL port 443 on one instance of a server. We have installed one of my portal/site where we are uploading files directly to other portal(onlyoffice) using SSL port 443 but however unique 443 port is restricted to same IP address of same server so both applications(our software portal/onlyoffice portal) both cannot be bound to same port 443 for SSL of same IP address.

Please provide us a solution for the above feasibility ASAP as we are planning to buy one OnlyOffice License portal ASAP.

**Comment by ibnpetr** [comment]
Hello 

> Please provide us a solution for the above feasibility ASAP as we are planning to buy one OnlyOffice License portal ASAP.

If you are going to purchse a license, feel free to [contact ONLYOFFICE Support](https://www.onlyoffice.com/support-contact-form.aspx), they will handle your request as a presale question and will help you as soon as possible.
