### ISSUE TITLE
How can I edit default.json? I can't find it.

### ISSUE THREAD

**Issue by FEliuze** [ONLYOFFICE/CommunityServer#236]
Hello!Help!Where is default.json?
My install-command is "sudo docker pull onlyoffice/documentserver"
My run-command is "sudo docker run -i -t -d -p 8080:80 onlyoffice/documentserver",
I tried to find it in docker containers but I failed...

**Comment by ShockwaveNN** [comment]
Please stop spamming this same issue in different repos
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/266
