### ISSUE TITLE
S3/Swift support?

### ISSUE THREAD

**Issue by intlabs** [ONLYOFFICE/CommunityServer#24]
Are there any plans to provide either S3 or OpenStack Swift support?

At the moment I think this could be hacked on by using a S3/Swift backed webdav gateway (https://github.com/hpcloud/swift-webdav), and I am looking into to using this approach within our organisation (though the swift-webdav code above needs updated for the current Openstack Keystone API).

**Comment by AnaMih** [comment]
1) S3 is provided, but there is no documentation about it. So please open the file web.storage, add the following and change disk to S3: 
 <add name="s3" type="ASC.Data.Storage.S3.S3Storage, ASC.Data.Storage">
      <property name="acesskey" value="" />
      <property name="secretaccesskey" value="" />
      <property name="bucket" value="" />
      <property name="cname" value="" />
      <property name="region" value="" />
    </add>

2) OpenStack Swift is not supported. You can do it basing on class 
https://github.com/ONLYOFFICE/CommunityServer/blob/master/common/ASC.Data.Storage/IDataStore.cs
example: 
https://github.com/ONLYOFFICE/CommunityServer/blob/master/common/ASC.Data.Storage/S3/S3Storage.cs
