### ISSUE TITLE
Error pinging host :8081, when trying to connect with the mail server

### ISSUE THREAD

**Issue by billcxx** [ONLYOFFICE/CommunityServer#242]
I'm using the installation script from here https://helpcenter.onlyoffice.com/server/docker/opensource/opensource-script-installation.aspx to setup the community server on one of my homelab servers (ubuntu 20.04). The installation process finishes properly.

But when I try to connect to the mail server, under the "Settings->Integration->Mail Server" tab, by clicking the connect button, it keeps showing this error: "Error pinging host **Mail-Server-IP**:8081" 

The Mail Server IP that I used is the public IP address of my home, and my router is forwarding all of the ports to this server, 25, 143, 993, 995, 110, 587, 3306, 8081, and port 83->80, 445->443 since 80 and 443 are already used by another server. 
The firewall of the current server is also enabled for all of the above ports.

I couldn't find any useful information online on how to debug this issue? Any help is appreciated!

### ----- update1------
Here are the commands that I executed

```Bash
wget https://download.onlyoffice.com/install/opensource-install.sh
sudo bash opensource-install.sh -md "MYDOMAINNAME"
```
and choose yes to go for the docker version.

This ended up loading four docker containers on my machine. onlyoffice/communityserver:10.5.3.1172, onlyoffice/mailserver:1.6.74, onlyoffice/documentserver:5.6.3.2, and mysql:5.7.26

![image](https://user-images.githubusercontent.com/3356113/92325445-e16b2c00-f018-11ea-855c-923e9434dd54.png)

So all the community server, document server, and mail server are on the same machine. 

Here is a `sudo netstat -tunlp` output. There are many nx* programs, those are remote desktop services by NoMachine.
![image](https://user-images.githubusercontent.com/3356113/92325758-0d87ac80-f01b-11ea-824d-1ad37b14f66d.png)

**Comment by Carazyda** [comment]
Hello @billcxx Please specify how you installed community server and mail server, which parameters in script do you use? Mail server on another machine?

**Comment by billcxx** [comment]
@Carazyda Thanks for the quick response! I update my question with more information. Please see the part update1, thanks!

**Comment by Carazyda** [comment]
If you install all in the one machine by our script - mail server configured automatically, you not need to setup it in portal settings. Please tell me - mail server is worked, you added a domain to it, created a mailbox?

**Comment by billcxx** [comment]
@Carazyda 

I did add my own domain name and a mailbox. 

I check the DNS setting by clicking the drop-down menu of "Mail->Settings->Mail Server->my own domain name -> DNS settings". The MX, SPF, and DKIM records all show a green checkmark before them. 

Don't know why, but after a reboot this pinging error is gone. Now the error message becomes "Error: Сould not get hostname"

![image](https://user-images.githubusercontent.com/3356113/92330546-96174480-f03d-11ea-80ad-869dffe650eb.png)

I'll close this issue since this is another problem. I need to look into this new problem first.

Thanks for your help
