### ISSUE TITLE
Monoserve randomly dies, NGINX throws 502

### ISSUE THREAD

**Issue by tpelado** [ONLYOFFICE/CommunityServer#248]
Good morning;

I've been using onlyoffice for the last few weeks, and its been great. But every once in a while, and for a reason I haven't found yet, the monoserve server dies and NGINX throws a 502. While restarting the monoserve service fixes the issue, I can't really just ssh into the thing everytime.

I'm using a container for the Com server & one for the Doc server.

Specs : 
8G of RAM
4G of SWAP
2cores
25G of disk space.
Running on Ubuntu 20.04.

I can provide anything log wise.

Thanks

Tanguy

**Comment by Carazyda** [comment]
Hello @tpelado Yes, we have a problem, that the mono crashes our site. But monoserve should be restarted automatically. And in the next version we working on stability monoserve and services. Thank you for your report.

**Comment by tpelado** [comment]
Alright.

Do you have any idea on how long the monoserve takes to restart when it crashes? Just so I know if I have to restart it manually or if I can wait a few minutes.

I'll wait for the next update then. Do you have any ETA?

Cheers

Tanguy

**Comment by Carazyda** [comment]
In normal it restarts in a few minutes (2-3min). The next version will be released within the next month.

**Comment by tpelado** [comment]
Alright, thanks.
