### ISSUE TITLE
changing the display in CRM/contact menu

### ISSUE THREAD

**Issue by saidiahd** [ONLYOFFICE/CommunityServer#25]
I am trying to change the display view of contacts, I want to add some other information field like contact address, last contact …
I have trying to change “ContactsTemplates.ascx” in “\web\studio\ASC.Web.Studio\Products\CRM\Templates” but with no effect.
Plz can I have more information about contact display modification process. 

Thx

**Comment by tatianatscherbakova** [comment]
Try to change the value of the key "web.client.cache.resetkey" in "\web\studio\ASC.Web.Studio\web.appsettings.config" to reset current cache or you can turn off bundle optimization by setting "web.client.bundling" to "false".
