### ISSUE TITLE
StackExchange.Redis.RedisConnectionException

### ISSUE THREAD

**Issue by eugenov** [ONLYOFFICE/CommunityServer#251]
Hello!
After installing Community Server for CentOS, according to official manual (https://helpcenter.onlyoffice.com/server/linux/community/linux-installation-centos.aspx), i see
```
StackExchange.Redis.RedisConnectionException
UnableToConnect on 127.0.0.1:6379/Interactive, Initializing, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, unanswered-write: 1954s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.519.65453

Description: HTTP 500.Error processing request.

Details: Non-web exception.
```
I did change MySQL root password before running communityserver-configure.sh with OK result.

**Comment by Carazyda** [comment]
Hello @eugenov Sorry, but this instruction is out of date. We update it in the next release. For now we recommend use our installation [script](https://helpcenter.onlyoffice.com/server/docker/opensource/opensource-script-installation.aspx).

**Comment by eugenov** [comment]
> 
> 
> Hello @eugenov Sorry, but this instruction is out of date. We update it in the next release. For now we recommend use our installation [script](https://helpcenter.onlyoffice.com/server/docker/opensource/opensource-script-installation.aspx).

This script install Document Server AND Community Server?

**Comment by eugenov** [comment]
I have SELinux disabled already. Files /etc/selinux/targeted/policy/policy.30 on their places, where they should be.

**Comment by Carazyda** [comment]
This script install Opensource Community Edition, that includes CommunityServer+DocumentServer+MailServer. Script can install docker version or package version. Also in docker version you can choose what install, you can install only CommunityServer. We recommend disable Selinux, or you can see our [troubleshooting](https://helpcenter.onlyoffice.com/server/linux/community/troubleshooting.aspx).

**Comment by eugenov** [comment]
Nothing in Troubleshooting fits.

**Comment by eugenov** [comment]
Derar Devs, is there any advices yjw to troubleshoot my installation? I have big plans on this software...

**Comment by Carazyda** [comment]
You can try disable SELinux, reboot server and try install again. Also we recommend use docker, it's more convenient. Or open a new issue with more details.

**Comment by eugenov** [comment]
SELinux was disabled at the moment I ran your script. OK, I will open new issue, thank you.
