### ISSUE TITLE
Editing shared documents w/o write permissions located on webdav folder

### ISSUE THREAD

**Issue by eugenov** [ONLYOFFICE/CommunityServer#254]
I have Community Server with connected webdav folder (nextcloud).
When i'm trying to edit read-only document, it stores all the modifications locally.
For example:
1. create file on nextcloud read-only shared folder with "111" content with nextcloud GUI
2. open this file with CommunityServer Document Editor
3. edit "111" to "11", save, close
4. open this file with nextcloud GUI
5. see no modifications (only "111" inside), it's OK
6. open this file with CommunityServer Document Editor
7. see "11" inside, it's not OK

How to set CommunityServer not to store read-only files modifications in its cache?

**Comment by HelenBelova17** [comment]
Hello @**eugenov** 
There is currently no way to customize Community Server not to store read-only files modifications in its cache.
Thank you for your suggestion. We will take it into consideration.
