### ISSUE TITLE
How to search files in specified folder

### ISSUE THREAD

**Issue by xunmeng2015** [ONLYOFFICE/CommunityServer#257]
Hi, i want to search file in specified folder (like common, trash), but i can only find this api.
![image](https://user-images.githubusercontent.com/15134608/96953049-cb5eef80-1522-11eb-84dc-01c2682d2508.png)
Could you tell me how to search files in children folder?

look forward to your reply.
THX.

**Comment by LinneyS** [comment]
Hi @xunmeng2015 
You can use https://api.onlyoffice.com/portals/method/files/get/api/2.0/files/%7bfolderid%7d
with parameter `filterValue` (https://api.onlyoffice.com/portals/filters)

But it will only be in the current folder, no search in the subfolder

**Comment by xunmeng2015** [comment]
Hi @LinneyS 
It helps me a lot. Thank you!
