### ISSUE TITLE
Installation failed with Workspace community version script. Debian 10.6

### ISSUE THREAD

**Issue by gbrea** [ONLYOFFICE/CommunityServer#258]
I was trying to install the Workspace package on a freshly installed and updated debian 10.
I used the installation script from the official page with the command `bash workspace-install.sh.`
The installation process started but stopped and threw this error message:
```bash
ERROR` 1146 (42S02) at line 228: Table 'onlyoffice.wiki_pages' doesn't exist
dpkg: error processing package onlyoffice-communityserver (--configure):
 installed onlyoffice-communityserver package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 onlyoffice-communityserver
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I tried to install it on a debian 9.13 and the script ran without problems and the Workspace was operational.
If I run the script again it tells me that `onlyoffice-communityserver is already installed` but I enter the ip of my machine from a browser and it does not connect.
Any idea why this behavior?

**Comment by Carazyda** [comment]
Hello @gbrea on debian10 this error means you have a problem with the database. Try to purge mariadb and mysql before install onlyoffice.

If onlyoffice installed - you don't need to run script again. If you can't access portal from a browser - please check that a nginx and monoserve is running, and check web.log for the errors.

**Comment by gbrea** [comment]
Thanks for your quick response.

The nginx service is stopped. I look at the log:
```
root@debianbase:~# tail /var/log/nginx/error.log 
2020/10/28 13:30:20 [info] 14492#14492: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:63
2020/10/28 13:39:38 [info] 28759#28759: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:63
2020/10/29 13:35:04 [info] 456#456: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:63
2020/10/29 13:35:04 [emerg] 456#456: mkdir() "/var/cache/nginx/onlyoffice" failed (2: No such file or directory)
```
I create the missing directories "nginx / onlyoffice" and restart the service. Now it does start. Even though I access the browser and get a 502 "Bad gateway"

I check the "monoserve" service and it is also stopped, I start it but it does not go.
```
● monoserve.service - FastCGI Mono server
   Loaded: loaded (/lib/systemd/system/monoserve.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-10-29 13:57:48 CET; 4s ago
  Process: 1817 ExecStartPre=/bin/bash -c test -e /var/run/onlyoffice || install -m 755 -o onlyoffice -g nginx -d /var/run/onlyoffice; rm -f /var/run/onlyoffice/onlyoffice.socket (code=exited, status=0/SUCCESS)
  Process: 1820 ExecStart=/usr/bin/hyperfastcgi4 /config=/etc/hyperfastcgi/onlyoffice /logfile=/var/log/onlyoffice/onlyoffice.log /loglevels=All (code=exited, status=1/FAILURE)
 Main PID: 1820 (code=exited, status=1/FAILURE)

Out 29 13:57:48 debianbase hyperfastcgi4[1820]: Mono: Unloading image /usr/lib/mono/gac/Mono.Posix/4.0.0.0__0738eb9f132ed756/Mono.Posix.dll [0x55a031f1c350].
Out 29 13:57:48 debianbase hyperfastcgi4[1820]: Mono: Assembly image '/usr/lib/mono/gac/System.Web/4.0.0.0__b03f5f7f11d50a3a/System.Web.dll' [0x55a03235f850] still loaded at shutdown.
Out 29 13:57:48 debianbase hyperfastcgi4[1820]: Mono: Assembly image '/usr/lib/mono/gac/System.Configuration/4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll' [0x55a0320a4b80] still loaded at shutdown.
Out 29 13:57:48 debianbase hyperfastcgi4[1820]: Mono: Assembly image '/usr/lib/mono/gac/HyperFastCgi/0.4.4.0__0738eb9f132ed756/HyperFastCgi.exe' [0x55a03262fd60] still loaded at shutdown.
Out 29 13:57:48 debianbase hyperfastcgi4[1820]: Mono: Assembly image '/usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll' [0x55a031f0dfe0] still loaded at shutdown.
Out 29 13:57:48 debianbase hyperfastcgi4[1820]: Mono: Assembly image '/usr/lib/mono/4.5/mscorlib.dll' [0x55a031eca980] still loaded at shutdown.
Out 29 13:57:48 debianbase hyperfastcgi4[1820]: Mono: Assembly image '/usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll' [0x55a0325d0660] still loaded at shutdown.
Out 29 13:57:48 debianbase hyperfastcgi4[1820]: Mono: Assembly image '/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll' [0x55a031f3a090] still loaded at shutdown.
Out 29 13:57:48 debianbase systemd[1]: monoserve.service: Main process exited, code=exited, status=1/FAILURE
Out 29 13:57:48 debianbase systemd[1]: monoserve.service: Failed with result 'exit-code'.
```

I look at the log that says: /var/log/onlyoffice/onlyoffice.log
```
root@debianbase:~# tail /var/log/onlyoffice/onlyoffice.log 
[2020-10-29 13:57:48Z] Debug   HyperFastCgi
[2020-10-29 13:57:48Z] Debug   Threadpool minw=100,minio=4,maxw=10000,maxio=200
[2020-10-29 13:57:48Z] Debug   Root directory: /var/www/onlyoffice/WebStudio
[2020-10-29 13:57:48Z] Debug   SimpleApplicationServer.CreateAppHost vhost=, vport=0
[2020-10-29 13:57:48Z] Debug   Listening on port: 0
[2020-10-29 13:57:48Z] Debug   Listening on address: /var/run/onlyoffice/onlyoffice.socket
[2020-10-29 13:57:48Z] Error   Could not start server
```
The /var/run/onlyoffice/onlyoffice.socket file does not exist.
I also don't know how to access the database, since it was installed with the installation script. I don't know the access credentials. I'm still a bit lost, any ideas? Thank you very much!!

**Comment by Carazyda** [comment]
All directories should have been created automatically during installation. If you have an errors during the installation on onlyoffice - please try install on fresh OS, without preinstalled db, like MariaDB or Mysql.

Credentials for connection to mysql database you can see at /var/www/onlyoffice/WebStudio/web.connections.config.

**Comment by gbrea** [comment]
Yes, it is just what I have done, the operating system is freshly installed. Debian 10.6 in a virtual machine on virtual-box, without a graphical environment, with the basic packages that are installed, and the only thing installed besides that is the openssh server.
And I have repeated the process twice ...

**Comment by Carazyda** [comment]
Please make sure the mariadb or mysql is not installed on a clean OS, and delete it (apt purge mariadb-server). If it not help - can you attach a full log of installation? Also you can try use docker version.

**Comment by gbrea** [comment]
I have reinstalled the OS and it has neither mysql nor mariadb installed. Now I'm going to install OnlyOffice again. How can I get a full log of the installation?

**Comment by gbrea** [comment]
I leave the result of the installation in this file:
[installation.log](https://github.com/ONLYOFFICE/CommunityServer/files/5463732/log.log)

**Comment by gbrea** [comment]
Indeed, as you told me, the problem was that mysql was installed. When I did a `systemctl status mysqld` or mysql, it replied that the service did not exist so I assumed it was not installed.
Removing the `mysql-common` package onlyoffice workspace installs without problem.
@Carazyda Thank you very much for your help!
