### ISSUE TITLE
How can i get task progress.

### ISSUE THREAD

**Issue by xunmeng2015** [ONLYOFFICE/CommunityServer#262]
Hello,
When i download multiple files and folders, i can not get the download url at first time and i don't know how to get the task progress. 
So could you tell me is there any apis i can get the task progress such as download, copy, delete and other operations.
THX.

**Comment by ShockwaveNN** [comment]
Hi, maybe this helps https://api.onlyoffice.com/portals/method/files/get/api/2.0/files/fileops

**Comment by xunmeng2015** [comment]
Thank you.
