### ISSUE TITLE
Custom Module with Docker

### ISSUE THREAD

**Issue by IrishWolf** [ONLYOFFICE/CommunityServer#266]
Hello,

kinda noob-question here, but I think that you can help me with it.
I want to try writing an custom module for OnlyOffice but I failed to locate the necessary directories.

OO Community (with Docs and Mail, all latest) is installed via Docker on Ubuntu 14.04.5 LTS. 
I've stored the files outside of the container like the instruction said (https://helpcenter.onlyoffice.com/installation/workspace-install-docker-integrated.aspx):
```
 -v /app/onlyoffice/CommunityServer/letsencrypt:/etc/letsencrypt \
 -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
 -v /app/onlyoffice/CommunityServer/data:/var/www/onlyoffice/Data \
 -v /app/onlyoffice/CommunityServer/logs:/var/log/onlyoffice \
 -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/DocumentServerData \
```

But the mentioned folders from the instruction für custom modules aren't found there (https://helpcenter.onlyoffice.com/installation/groups-custom-modules.aspx).

Am I just blind or do I need to store more folders outside of the container or did I just installed the wrong version?

**Comment by Carazyda** [comment]
Hello @IrishWolf For adding custom modules you need to build from open source of CommunityServer. In docker image already compiled version.

**Comment by IrishWolf** [comment]
That's unfortunate. The Docker was a great way to separate the Installation from the Server without unnecessary VMs or Routing :/
