### ISSUE TITLE
Android, iOS

### ISSUE THREAD

**Issue by Abraka** [ONLYOFFICE/CommunityServer#269]
OnlyOffice DOCs has a mobile app for android and iOS, but I cant find any for CommunityServer. Why there isnt one? Without mobile app, community server is at big disadvantage.

**Comment by Carazyda** [comment]
Hello @Abraka Sorry, but we don't have an mobile app for CommunityServer. For now we development a new platform, that will be mobile adaptive, and i hope you enjoy it.

**Comment by Abraka** [comment]
I hope so too :+1:  Any ETA? ...yesterday was already late...

**Comment by Carazyda** [comment]
We do not have specific terms of release, so as not to upset you, but we really try to release this year.

**Comment by Abraka** [comment]
ok, thx for info.
