### ISSUE TITLE
Build was successful but while running project from Visual Studio it ran into errors

### ISSUE THREAD

**Issue by samdubey** [ONLYOFFICE/CommunityServer#27]
Step 1: Cloned Repository
Step 2: Build (Successful)
![image](https://cloud.githubusercontent.com/assets/4013722/10505642/385c5084-732d-11e5-860b-69c20418499f.png)
Step 3: Web.Config Errors  ( managed to clear this)
![image](https://cloud.githubusercontent.com/assets/4013722/10505694/c1db0c60-732d-11e5-8984-fe51e5405b18.png)

Step: 4 JWTLogin.ashx and SAMLogin.ashx seems to be missing from solution
![image](https://cloud.githubusercontent.com/assets/4013722/10505930/f97ee04a-732f-11e5-9cf3-b56ca8031a5e.png)

Finally application was kicked off in browser

but unable to see CSS and JS file loaded from App_Data folder

**Comment by AnaMih** [comment]
Do you run the project directly from VS or configure IIS for already builded version. Probably, the issues are caused by the IIS Settings.
