### ISSUE TITLE
How to change server name in Talk?

### ISSUE THREAD

**Issue by ww7** [ONLYOFFICE/CommunityServer#277]
![](https://api.monosnap.com/file/download?id=2KlnQoQsse31uppJ4Db4URb6pptAhp)
How to change server name in Talk?

Changing HOSTNAME of `onlyoffice/communityserver` docker container has no effect.

**Comment by Carazyda** [comment]
Hello @ww7 You can change it in the portall settings by setup custom domain name.

**Comment by ww7** [comment]
Oh. Thanks!
