### ISSUE TITLE
Community server Folder sharing

### ISSUE THREAD

**Issue by xunmeng2015** [ONLYOFFICE/CommunityServer#279]
For folder a. group A access by 1(read and write), group B access by 2(read only), all user in group A is also in group B. However, after i set this configuration, all user in group A's access by 2(read only). What can i do?

**Comment by HelenBelova17** [comment]
Hello @xunmeng2015 
We have this mechanism of permission priority. 
![Screenshot_1082](https://user-images.githubusercontent.com/31805700/111125022-34064180-8582-11eb-83dc-a0b0d3162d2e.png)

For more information you can visit https://helpcenter.onlyoffice.com/userguides/groups-tipstricks-documents-folder-permissions.aspx.

**Comment by xunmeng2015** [comment]
Hello @HelenBelova17 , so the best way is to provide individual permissions (**Read and Write** here) to every user in group A?
![image](https://user-images.githubusercontent.com/15134608/111126992-4a29f700-85ae-11eb-825b-5b372804be73.png)
