### ISSUE TITLE
ONLYOFFICE run from visual studio 2012 goes into Redirection Loop

### ISSUE THREAD

**Issue by samdubey** [ONLYOFFICE/CommunityServer#28]
Hello Team,

I was able to compile and trying to run ONLYOFFICE Community Edition from VS2012

it goes into redirection loop as there is ONLYOFFICE installation already on Windows Machine under Program Files

Can you please let me know how to fix this issue

Thanks,

Sameer

**Comment by AnaMih** [comment]
Do you run the project directly from VS or configure IIS for already builded version. Probably, the issues are caused by the IIS Settings.

**Comment by samdubey** [comment]
I ran project from VS Directly

**Comment by AnaMih** [comment]
Please specify how do you build the solution and what project do you open in VS
You should create an empty solution in VS and configure dependences listed in build/msbuild/build.proj. 
The dependences should be built in the same sequence as in build/msbuild/build.proj
You also can build the solution using the file build/Build.bat and running the project web\studio\ASC.Web.Studio\ASC.Web.Studio.csproj
