### ISSUE TITLE
Export of contacts

### ISSUE THREAD

**Issue by dslengel** [ONLYOFFICE/CommunityServer#294]
Hello,

allways when I try to export my contacts I got this issue:
Unknown column 'f.thumb' in 'field list'

So I'm not able to receive the file.

Can you help me by that?

**Comment by Carazyda** [comment]
Hello @dslengel Seems that you database is not fully updated to the last version. How did you update the communityserver? Please try to execute `Sql/onlyoffice.upgradev111.sql`.

**Comment by dslengel** [comment]
I_m using Windows Server.
How do I execute Sql/onlyoffice.upgradev111.sql on that platform?

Am Fr., 21. Mai 2021 um 11:02 Uhr schrieb Mike Grunin <
***@***.***>:

**Comment by Carazyda** [comment]
You can use command line and mysql command. For this you need cd to your mysql server bin folder, and run `mysql -u root -pyourpassword -D onlyoffice`, then `source \path\to\your\sql\file` (better way copy the sql file to bin folder). Or you can use the gui sql manager, for example HeidiSQL.

**Comment by dslengel** [comment]
Thanks.
I've installed mySQL Workbench. Does an upgrade work inside this
program either?
If yes. Can you explain how to do it?

Am Fr., 21. Mai 2021 um 13:17 Uhr schrieb Mike Grunin <
***@***.***>:

**Comment by dslengel** [comment]
You asked: How did you update the communityserver?
I downloaded the setup and started it. Have I done something wrong

Am Fr., 21. Mai 2021 um 11:02 Uhr schrieb Mike Grunin <
***@***.***>:

**Comment by Carazyda** [comment]
You need to connect to your local mysql server, in left panel Navigator switch to Schemas, and select onlyoffice database. Then open the sql file, and execute it.

**Comment by dslengel** [comment]
Here is what I see.
Is this the right place? If it is so, please tell me, what I should do there?
<img width="1128" alt="Screenshot 2021-05-21 175027" src="https://user-images.githubusercontent.com/79863061/119164797-11e6df00-ba5d-11eb-8d21-5e1c19c7efca.png">

**Comment by Carazyda** [comment]
Yes, that's it. Then please select File->Open a sql file. And execute it after opening.

**Comment by dslengel** [comment]
I'm really sorry but don't understand what to do. Because it's an area that
I haven't had much to do with before.
You write that I should open an sql file. Just which file do you mean? And
what exactly do you mean by opening?
For me it would be easier if you showed me the way / the file and most
importantly what it is supposed to do. What is the goal, or why does it
have to be carried out now? What should this have to do with an update that
I have been doing weeks ago?

Thanks for your help,
Dirk

Am Fr., 21. Mai 2021 um 20:40 Uhr schrieb Mike Grunin <
***@***.***>:

**Comment by Carazyda** [comment]
If you are not familiar with the interface, you can use hotkeys. To open the sql file use Ctrl + Shift + O and select this file C: \ Program Files (x86) \ Ascensio System SIA \ CommunityServer \ Sql \ onlyoffice.upgradev111.sql. Then use Ctrl + Shift + Enter to execute the sql script. This must be done in order to update the database to the end, because it is possible that some errors occurred during the update. If this does not help, please send a screenshot of the error.

**Comment by dslengel** [comment]
Thanks, I'll check it out.
AND: It work's
AND: Thank you for you explanation

Could you help me about the last question?
ControlPanel, No Backup #276

Am So., 23. Mai 2021 um 12:02 Uhr schrieb Mike Grunin <
***@***.***>:

**Comment by Carazyda** [comment]
I'm glad to hear that. We are thinking about how to help you in #276 issue.
