### ISSUE TITLE
Cannot Build solution after pulling v11.5.2

### ISSUE THREAD

**Issue by bugMaker-237** [ONLYOFFICE/CommunityServer#302]
Hello guys.
Thanks for the awesome work. I have been following the project for a while now, I pulled the latest master version i.e version 11.5.2 and tried to build. The build failed. It seems that some projects are missing : ASC.Data.Encryption, ASC.Files.ThumbnailBuilder and ASC.SsoAuth.Svc.
Can you guys please help me figure out what i'm doing wrong ?

**Comment by Carazyda** [comment]
Hello @bugMaker-237 Sorry for this situation. We fixed this with pull request #304.

**Comment by bugMaker-237** [comment]
Build done! Everything seems to be alright. Thanks.
