### ISSUE TITLE
Name Change: OnlyOffice is too similar to OnlyFans

### ISSUE THREAD

**Issue by anthonybudd** [ONLYOFFICE/CommunityServer#306]
I wanted to address the elephant in the room and ask if anyone has considered renaming this project? I cant help but think OnlyOffice is too close to OnlyFans.

I have suggested this software to two clients and both times they chuckled and responded "OnlyFans". Now OF has reached mainstream adoption I think the "Only-" prefix is a no no for all software going forward (IMHO). I honestly believe that keeping the current name will negatively impact adoption despite all of the great features it provides (again IMHO).

Does anyone else have any comments about this?

**Comment by hellonadya** [comment]
Hello! Thanks for reaching out, we appreciate that. But we do not plan to change our name. This is the brand we love, we've been working on it for 11 years now (OnlyFans is much younger than that).

**Comment by anthonybudd** [comment]
Unfortunately that's not how branding works, it's not about who's first, its about who's got the most name recognition and I think that battle is forever lost.

 `This is the brand we love, we've been working on it for 11 years now`
This project was called TeamLab as of 2014 🙃

**Comment by hellonadya** [comment]
OK, you got me! The project called ONLYOFFICE turned 11 years in 2021 but it was rebranded ONLYOFFICE only in July 2014
(still older than OnlyFans, but as you've said that's not the point here) 

We love this project and this name that was actually obtained a little later than I said before. 

At the moment changing the naming is off the table. If we ever feel that the `only` prefix is a threat to its future, we'll reconsider it. 

I'm closing the issue (I would prefer to leave it as a discussion for the community but I don't see discussions enabled for this repo).
