### ISSUE TITLE
File names inside the archive

### ISSUE THREAD

**Issue by test-OnlyOffice** [ONLYOFFICE/CommunityServer#311]
Good afternoon. When testing the server version, we found a serious problem in the method of archiving backup copies of user files. Inside the archive, all user files are stored by their id and there is no association of file names with their id. In this case, if the user deletes the file, it is not possible to find the owner of the file or the file itself in the backup copy. This is a significant drawback that jeopardizes the very process of restoring users ' files.

**Comment by Carazyda** [comment]
Hello @test-OnlyOffice the backup file is used only for recovery in our portal. In this case, everything will be restored where it should be.

The association of id files and their names are stored in our database.

**Comment by test-OnlyOffice** [comment]
> Hello @test-OnlyOffice the backup file is used only for recovery in our portal. In this case, everything will be restored where it should be.
> 
> The association of id files and their names are stored in our database.

what if we raised all the services on our servers? How to find the database in the backup and get the associations of the file names and their id from there?

**Comment by test-OnlyOffice** [comment]
> Hello @test-OnlyOffice the backup file is used only for recovery in our portal. In this case, everything will be restored where it should be.
> 
> The association of id files and their names are stored in our database.

and for example, we do not want to restore the entire portal - but only get a specific file with a specific name

**Comment by Carazyda** [comment]
I didn't understand what you mean about services. You can deploy them however you like, only we don't have instructions for that. With the default installation, all services are located on the same server as the site.

The backup file contains a database, the list of files can be found in the table files_file.

**Comment by test-OnlyOffice** [comment]
> I didn't understand what you mean about services. You can deploy them however you like, only we don't have instructions for that. With the default installation, all services are located on the same server as the site.
> 
> The backup file contains a database, the list of files can be found in the table files_file.

in the files_file table for some reason there are no file names that users have stored in the only office

**Comment by test-OnlyOffice** [comment]
> I didn't understand what you mean about services. You can deploy them however you like, only we don't have instructions for that. With the default installation, all services are located on the same server as the site.
> 
> The backup file contains a database, the list of files can be found in the table files_file.

Thank you very much - this is what you need !!
