### ISSUE TITLE
update failed onlyoffice/communityserver:11.5.2

### ISSUE THREAD

**Issue by RooyeKhat** [ONLYOFFICE/CommunityServer#320]
Hi
i update manually in control panel communityserver
but when download and update click now docker pending in restart status
Restarting (246) About a minute ago
but now not start 

` onlyoffice/communityserver:11.5.2.1542   "/app/run-communit..."   32 minutes ago      Restarting (246) About a minute ago `

any one can help me 

Thanks

**Comment by RooyeKhat** [comment]
Even i try to docker exec -it xxx bash
show : 
`Error response from daemon: Container xxx is restarting, wait until the container is running`

and any time when restart docker show 
`xxxx        onlyoffice/communityserver:11.5.2.1542   "/app/run-communit..."   44 minutes ago      Restarting (246) 58 seconds ago                                    onlyoffice-community-server`
 docker logs -f xxxx
```
* Restarting nginx nginx                                                       start-stop-daemon: warning: failed to kill 89: No such process
                                                                         [ OK ]
Document Server is up
MAIL_SERVER_API_HOST not correct
+ exit 502

Thanks

```

**Comment by Carazyda** [comment]
Hello @RooyeKhat How did you install Onlyoffice? Mail Server is running? Did you updated a Control Panel first?

**Comment by RooyeKhat** [comment]
yes i updated control panel first and next communityserver
