### ISSUE TITLE
recover file

### ISSUE THREAD

**Issue by makhan111** [ONLYOFFICE/CommunityServer#326]
Hi!
I have a site about Ayahuasca retreat and its some files are not recovered.Guide me how to recover it?
thnx.......

**Comment by Carazyda** [comment]
Hello @makhan111 What do you mean? You have run Onlyoffice CommunityServer, and trying backup-restore? Please describe in more details, how did you run this, your case step by step, and errors in the logs?

> site about Ayahuasca retreat

**Comment by Trippydelics** [comment]
I have this [magic mushrooms uk](https://trippydelics.co.uk/) site I did for a client, it keeps getting this malware "Wypii2" in the form of plugin.

**Comment by Carazyda** [comment]
I've no idea what you are talking about, please create a new issue if this is *really* a problem with ONLYOFFICE, and describe it step by step.
