### ISSUE TITLE
docker nginx Cannot allocate memory

### ISSUE THREAD

**Issue by mrshengzyzy** [ONLYOFFICE/CommunityServer#327]
I use docker run communityServer and got this error:
```bash
2021/08/17 11:47:09 [emerg] 78879#78879: malloc(257698035840) failed (12: Cannot allocate memory)
2021/08/17 11:47:09 [alert] 78875#78875: worker process 78878 exited with fatal code 2 and cannot be respawned
```
and the memory looks good
```bash
root@eci-6b54bbb4ef54448b8abc35f167fe6a62:/# free -hm
             total       used       free     shared    buffers     cached
Mem:          9.9G       349M       9.6G       284K       468K        26M
-/+ buffers/cache:       323M       9.6G
Swap:           0B         0B         0B
```

**Comment by Carazyda** [comment]
Hi @mrshengzyzy Please describe where you get this error? How did you start the docker container for CommunityServer?

**Comment by mrshengzyzy** [comment]
thx to apply, @Carazyda 

```bash
sudo docker run -i -t -d --restart=always --name onlyoffice-community-server -p 80:80 \
  -v /app/onlyoffice/CommunityServer/data:/var/www/onlyoffice/Data \
 -v /app/onlyoffice/CommunityServer/logs:/var/log/onlyoffice \
 onlyoffice/communityserver:9.1.0.393
```

1. We do not use `--privileged` flag
2. The communityserver version is `9.1.0.393` which use `service` insteadof `systemctl`
3. The CRI implements is `kata-container` but not `runc`

It's strange why `nginx` try  to malloc 239Gi memory.

**Comment by mrshengzyzy** [comment]
I find the point, ` worker_connections` is too large!

When  runtime is `kataruntime`, command  `ulimit -n` returns `1073741816` and when  runtime is `runc`, command  `ulimit -n` returns `1048576`.
Too large ` worker_connections`  can cause `nginx` to allocate much more memory, see this page: http://mailman.nginx.org/pipermail/nginx/2020-June/059575.html

So the solution is to set `NGINX_WORKER_CONNECTIONS` to a proper value.

And I'll look up this issue in the `kata` project.

**Comment by mrshengzyzy** [comment]
I created an issue to track: https://github.com/kata-containers/kata-containers/issues/2462

Close this issue.
