### ISSUE TITLE
Has a plan to port CommunityServer to MVC and NetCore

### ISSUE THREAD

**Issue by HengzheLi** [ONLYOFFICE/CommunityServer#333]
As title, just check the installation documentation. Found that, CommunityServer is depend on mono in Linux and IIS in windows. 

I think it might be simplify the deployment model if it can port to netcore.

**Comment by Carazyda** [comment]
Hello @HengzheLi Yes, we did it in our new product AppServer. We will announce this shortly.

**Comment by HengzheLi** [comment]
Great news.
