### ISSUE TITLE
After loading the excel file, the browser automatically scrolls to the excel display position

### ISSUE THREAD

**Issue by scholar-xia** [ONLYOFFICE/CommunityServer#336]
After my page is loaded, my onlyoffice is at the bottom of the page. When onlyoffice loads the excel file, the browser automatically scrolls to the excel display position. How do I set up onlyoffice so that the browser does not automatically scroll to the onlyoffice iframe element position .

**Comment by ShockwaveNN** [comment]
Please do not duplicate issues in different repos

https://github.com/ONLYOFFICE/DocumentServer/issues/1425
