### ISSUE TITLE
Onlyoffice communityserver can't running in None-Internet LAN?

### ISSUE THREAD

**Issue by Handsome1080P** [ONLYOFFICE/CommunityServer#353]
Onlyoffice communityserver can't running in None-Internet LAN? After instlled I moved the server to the the private network with no internet.The fking login page need 10+ seconds to open,so slowly!what going on?

**Comment by Carazyda** [comment]
Hello @Handsome1080P If you use docker installation - you need to change docker dns servers to your local. More information in our [instruction](https://helpcenter.onlyoffice.com/installation/groups-install-docker.aspx).

**Comment by Handsome1080P** [comment]
> Hello @Handsome1080P If you use docker installation - you need to change docker dns servers to your local. More information in our [instruction](https://helpcenter.onlyoffice.com/installation/groups-install-docker.aspx).

there is no DNS server in my private network.

**Comment by Carazyda** [comment]
> Docker specifies Google DNS servers by default. If your ONLYOFFICE Groups is not going to have access to the Internet, we recommend that you change the default Docker DNS address to the address of your local DNS server. To do that go to the /etc/default/docker file and change the IP address in the following line to the IP address of a DNS server in your local network:
docker_OPTS="--dns 8.8.8.8"
For the RPM based operating systems like CentOS, the configuration file can be located here: /etc/docker/daemon.json

**Comment by Handsome1080P** [comment]
> > Docker specifies Google DNS servers by default. If your ONLYOFFICE Groups is not going to have access to the Internet, we recommend that you change the default Docker DNS address to the address of your local DNS server. To do that go to the /etc/default/docker file and change the IP address in the following line to the IP address of a DNS server in your local network:
> > docker_OPTS="--dns 8.8.8.8"
> > For the RPM based operating systems like CentOS, the configuration file can be located here: /etc/docker/daemon.json

Really need a DNS?and must connect to internet? If change the DNS localhost,there is still no internet and can resolve any domains

**Comment by Carazyda** [comment]
If you use a local network - it must have dns server, maybe it your local machine. The problem is that the docker is trying to reach the dns of the google server, hence this timeout occurs when accessing our application. If you specify a local dns server to which you have access, there will be no delay. The Internet has nothing to do with it.

**Comment by Handsome1080P** [comment]
> If you use a local network - it must have dns server, maybe it your local machine. The problem is that the docker is trying to reach the dns of the google server, hence this timeout occurs when accessing our application. If you specify a local dns server to which you have access, there will be no delay. The Internet has nothing to do with it.

U meant only need a DNS server can respond not need  the DNs server to resolve?I can host a Dnsmasq without upstream at local host.

**Comment by Carazyda** [comment]
> a DNS server can respond not need the DNs server to resolve?!

Yes, that should help.

**Comment by Handsome1080P** [comment]
> > a DNS server can respond not need the DNs server to resolve?!
> 
> Yes, that should help.

Thx a lot
