### ISSUE TITLE
E-mail (imap) is not marked as read when received on another software

### ISSUE THREAD

**Issue by dominiaz** [ONLYOFFICE/CommunityServer#358]
When I receive couple of e-mails on the phone with mail app like outlook and mark all of them as readed and then I am logging to Onlyoffice e-mail all of thiese e-mails are still marked as not readed.

They should be readed already on onlyoffice.

Why? Is it a bug/setting or what?

**Comment by Carazyda** [comment]
Hello @dominiaz Our Mail module is only mailaggregator, that download emails, dont have imap synchronization. In the next version we will release imap service, that work with our Mail Server.
