### ISSUE TITLE
execute the ManageServices.bat --install-all command 

### ISSUE THREAD

**Issue by xbitlabs** [ONLYOFFICE/CommunityServer#37]
Windows 10 ，execute the ManageServices.bat --install-all command ，
'sc' is not recognized as an internal or external command,
operable program or batch file.
'sc' is not recognized as an internal or external command,
operable program or batch file.
'sc' is not recognized as an internal or external command,
operable program or batch file.
'sc' is not recognized as an internal or external command,
operable program or batch file.
'sc' is not recognized as an internal or external command,
operable program or batch file.
'sc' is not recognized as an internal or external command,
operable program or batch file.
'sc' is not recognized as an internal or external command,
operable program or batch file.

**Comment by alexeybannov** [comment]
You will need to add the path to sc.exe ("c:\windows\system32\") in your Path environment variable.
