### ISSUE TITLE
Missing onlyoffice.socket in "/var/run/onlyoffice/" after .deb installation

### ISSUE THREAD

**Issue by C-Duv** [ONLYOFFICE/CommunityServer#38]
I have performed a .deb installation (following [Installing Community Server for Linux on a local server](http://helpcenter.onlyoffice.com/fr/server/linux/community/linux-installation.aspx) guide) on my Debian 8 server.

I get the following errors in the Nginx server logs:

```
[crit] 17700#0: *14 connect() to unix:/var/run/onlyoffice/onlyoffice.socket failed (2: No such file or directory) while connecting to upstream, client: 2.2.2.2, server: docs.example.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice.socket:", host: "docs.example.com"
[crit] 17700#0: *14 connect() to unix:/var/run/onlyoffice/onlyoffice2.socket failed (2: No such file or directory) while connecting to upstream, client: 2.2.2.2, server: docs.example.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice2.socket:", host: "docs.example.com"
[error] 17700#0: *14 no live upstreams while connecting to upstream, client: 2.2.2.2, server: docs.example.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://fastcgi_backend", host: "docs.example.com", referrer: "http://docs.example.com/"
```

It seems that sockets in `/var/run/onlyoffice/` are missing.
`/var/run/onlyoffice/` is indeed empty, is owned by `onlyoffice:www-data` and has the following permissions: `drwxr-sr-x`.

I tried restarting monoserve\* and onlyoffice\* in hope theses sockets would be recreated: no luck.

How can I manually create them?

**Comment by Dean13** [comment]
No creation need, you may link the two sockets between with performing the following command from the inside of a docker-container: 
`ln -s /var/run/onlyoffice/onlyoffice2.socket /var/run/onlyoffice/onlyoffice3.socket`
