### ISSUE TITLE
i can not build ASC.Web.Studio.csproj in vs2012,lost many files and projects.

### ISSUE THREAD

**Issue by hxsam** [ONLYOFFICE/CommunityServer#40]
hi, 

I can not found the Directory:  $(ASCDir)common\ASC.ActiveDirectory\ and ASC.ActiveDirectory.csproj
.
and  in ASC.Web.Studio\HttpHandlers  Directory:JwtHandler.cs and SamlHandler.cs can not found.

I have manually referenced all project DLL or related the csproj which are needed for the ASC.Web.Studio.csproj . ...Which is too tired.

The following figure is above

![onlyofficevs2012](https://cloud.githubusercontent.com/assets/15061658/15989022/e2583f28-309a-11e6-9bc8-0804347eb877.png)
![onlyofficevs2012-1](https://cloud.githubusercontent.com/assets/15061658/15989023/e26024a4-309a-11e6-9fe1-807ec24f2cf6.png)

**Comment by alexeybannov** [comment]
fixed
