### ISSUE TITLE
真是一个坑，换成中文就是这个错误了，搭建了半天，编译环境不成功

### ISSUE THREAD

**Issue by hxsam** [ONLYOFFICE/CommunityServer#41]
严重缺少文档，少文件少引用。

想对里面这句修改下，折腾了一天，发现根本没办法编译。

![bug](https://cloud.githubusercontent.com/assets/15061658/15990035/ba5c372e-30bb-11e6-99a0-9ef8dbd45e06.png)
![bug2](https://cloud.githubusercontent.com/assets/15061658/15990038/c41b1988-30bb-11e6-976c-df2b193fe405.png)

**Comment by Dean13** [comment]
The issue was fixed in our closed repo in the 8.9.0.

**Comment by Dean13** [comment]
Issue is closed according to 8.9.0 release.
