### ISSUE TITLE
Send Mail Via SMTP

### ISSUE THREAD

**Issue by chikafood** [ONLYOFFICE/CommunityServer#42]
I've installed hmailserver on local computer and set the default port and IP on setting page. it works perfectly when press "Send Test Mail" and with "Mail" section , but mail system doesn't work properly for other parts  ( like "Please activate your email entered while registering to get access to all the portal features." or "activating users" )

Should I set the SMTP port and IP somewhere else ?

**Comment by AlexeySafronov** [comment]
There can be many reasons, you'll have to attach /var/log/onlyoffice/svc.notify.log

**Comment by massapf** [comment]
Hi!
Add mail account works with Exchange 2010? 
I can receive email but can not send.
Everything is ok with the relay configuration and smtp tests with telnet in console is ok.

Any suggestion?

Thanks,
Carlos

**Comment by AlexeySafronov** [comment]
Do you have mail-daemon message in inbox? There is a reason of your problem.

**Comment by massapf** [comment]
Hi Alexey, Yes, it´s 5.7.

The problem was with the Exchange SSL certificate, but I have a user who is not sending e-mail reporting the same error.

Other users are OK

Thank you for your help

Carlos
