### ISSUE TITLE
Resest two-factor authentication

### ISSUE THREAD

**Issue by mastipgithub** [ONLYOFFICE/CommunityServer#428]
Hi, I am have a problem. One of users of my selfhosted portal lost phone and he did not print backup codes. 
I would like to reset two-factor authentication for him or for all users. I tried reset password for him but after opening link generated by portal there is screen with two-factor authentication. After this I turned off and turn on two-factor authentication. But this does not reset 
two-factor authentication.
I need Your help i don't want to delete this user account and create new.

**Comment by Carazyda** [comment]
Hello @mastipgithub. You can reset the 2FA application for a user in their profile, in the "People" module.
![image](https://user-images.githubusercontent.com/12935052/195567262-ea5475c5-c3af-4787-9910-ea36cdbf8b3e.png)

**Comment by mastipgithub** [comment]
My mistake, I haven't seen it
