### ISSUE TITLE
Old machine code with spaces

### ISSUE THREAD

**Issue by mastipgithub** [ONLYOFFICE/CommunityServer#429]
Hello, I am migrating portal docker version to new machine. First I made portal backup from control panel. Then I read that If i want import old portal to new portal, I need install new portal with old machine key parameter. I am installing by script workspace-install and my problem is machinekey parameter is with spaces -mk Vskoproizvolny Salt par Chivreski and I can’t start script.

**Comment by Carazyda** [comment]
Hello @mastipgithub Please download this [script](https://download.onlyoffice.com/install/install.sh) and run it with parameter
`-mk "Vskoproizvolny Salt par Chivreski"`

**Comment by mastipgithub** [comment]
It doesn not work. I tried with ””  Wrong parameter Salt

**Comment by mastipgithub** [comment]
It worked!
