### ISSUE TITLE
can not search by CJK

### ISSUE THREAD

**Issue by renothing** [ONLYOFFICE/CommunityServer#43]
hi, I found that the current version can not search by CJK characters like chinese or japanese. only Latin alphabet works fine.

**Comment by xlins** [comment]
I found the same issue in the latest version.

**Comment by JohnPerkin** [comment]
Hello!
Search by CJK characters is implemented in Community Server 9.0 which soon will be released. We will inform you about its releasing in our [Changelog](https://github.com/ONLYOFFICE/CommunityServer/releases).

**Comment by xlins** [comment]
So great, thanks a lot for all your hard work!
