### ISSUE TITLE
Corrupted installation package

### ISSUE THREAD

**Issue by funmix** [ONLYOFFICE/CommunityServer#434]
Hi Good day,

I'm trying out the Workspace few days ago and notice the installer is corrupted.

![Error](https://user-images.githubusercontent.com/20920616/201241139-cbd176f2-118d-45bb-90e9-1eac453be784.PNG)

I downloaded multiple copies they are all the same. Try on Windows Server 2019 and 2022 doesn't work either. I'm downloading from this website (https://www.onlyoffice.com/download-workspace.aspx#workspace-community)

**Comment by Carazyda** [comment]
Hello @funmix Yes, we had a problem. We have updated the installer on the site. Thank you for pointing out the error.
