### ISSUE TITLE
DocsApi not defined error

### ISSUE THREAD

**Issue by GOVYANSONG** [ONLYOFFICE/CommunityServer#436]
Error:

while accessing http://localhost/web-apps/apps/api/documents/api.js: DocsApi not defined.

OS:

Linux mk8smaster 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

docker image:

onlyoffice/communityserver:12.1.0.1760
onlyoffice/controlpanel:3.1.1.467

question:

is DocsApi only accessible from https?

**Comment by Carazyda** [comment]
Hello @GOVYANSONG Please describe in more details, how did you install Onlyoffice Workspace? Or you use Onlyoffice Groups? This error from portal settings /Management.aspx?type=17 ? Please check the status of DocumentServer docker container.

**Comment by GOVYANSONG** [comment]
I was trying to follow the instructions given at https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example/nodejs. Instead install on linux box, i run communityserver docker given at https://hub.docker.com/r/onlyoffice/communityserver/.

**Comment by Carazyda** [comment]
If you need to install DocumentServer integrated with CommunityServer, you can use Onlyoffice Workspace. Instructions for installing [Github](https://github.com/ONLYOFFICE/Docker-CommunityServer#installing-onlyoffice-workspace) or [Helpcenter](https://helpcenter.onlyoffice.com/installation/workspace-install-docker.aspx). We recommend using our installation scripts.

**Comment by GOVYANSONG** [comment]
thanks for the quick response. I was able to proceed further. i got this error when trying to create a document e.g. excel spreadsheet:

![error](https://user-images.githubusercontent.com/36177352/204148647-f067f7b2-cec3-4dde-869e-2662ec4342c8.png)

**Comment by GOVYANSONG** [comment]
after resolved the previous error, now getting: 

![error](https://user-images.githubusercontent.com/36177352/204154267-ac337c4f-5a54-4296-a161-89cd62544396.png)
