### ISSUE TITLE
portal blocked in migration

### ISSUE THREAD

**Issue by annibal1** [ONLYOFFICE/CommunityServer#437]
Good morning
Yesterday I unable I clicked in the migration of the panel to Google Drive and 24 hours passed and still connecting to the site he writes me
Portal migration
in progress.
How can I cancel this operation that is doing ??
I installed OnlyOffice Workspace with Docker on a Ubuntu machine
Is there a solution to be able to cancel the migration and bring the operating panel back?
Thank you

**Comment by Carazyda** [comment]
Hello @annibal1 please check the logs for errors. To return the portal to its normal state, you need to change the value in the status column to 0 in the tenants_tenants table in the MySQL database.

**Comment by annibal1** [comment]
Excuse me where I can find that table that I don't find it on my server docker? let me know a thousand thanks cordally greet


Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

Da: Mike ***@***.***>
Inviato: martedì 29 novembre 2022 16:50
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [ONLYOFFICE/CommunityServer] portal blocked in migration (Issue #437)


Hello @annibal1<https://github.com/annibal1> please check the logs for errors. To return the portal to its normal state, you need to change the value in the status column to 0 in the tenants_tenants table in the MySQL database.

**Comment by Carazyda** [comment]
If you run docker please follow this commands:
`sudo docker exec -it onlyoffice-community-server bash`
`mysql -u root -pmy-secret-pw -h onlyoffice-mysql-server -D onlyoffice`
`select * from tenants_tenants;`
`update tenants_tenants set status=0 where id=1;` (id is matched to your portal)

**Comment by annibal1** [comment]
ok Solved Thank You
