### ISSUE TITLE
Backup not found

### ISSUE THREAD

**Issue by annibal1** [ONLYOFFICE/CommunityServer#438]
Since I have a problem with the portal and I would like to backup from the server but following the guide I do not find the backup by me previously created locally
Docker use on Ubuntu Server 20.04
Your guide talks about these paths
Docker Container. Folders in The Community Server Docker Containers (Not on the Host Computer) Which Contain OnlyOffice Data Are:

/Var/Log/OnlyOffice
/VAR/www/OnlyOffice/Data
/Var/Lib/Mysql
But in those paths on my server there is no backup Localhost ...
Can you give me some help to find the backup so can I restore my server?
thank you

**Comment by Carazyda** [comment]
Hello @annibal1 It looks like you have found a manual backup guide, i.e. easy copying of data folders. If you made a backup in the control panel, then the backup file is stored at the path you specified. If it was a temporary backup, then it is deleted after 24 hours.

**Comment by annibal1** [comment]
It looks like you have found a manual backup guide, i.e. easy copying of data folders. If you made a backup in the control panel, then the backup file is stored at the path you specified. If it was a temporary backup, then it is deleted after 24 hours.


Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

Da: Mike ***@***.***>
Inviato: martedì 29 novembre 2022 15:03
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [ONLYOFFICE/CommunityServer] Backup not found (Issue #438)


Hello @annibal1<https://github.com/annibal1> It looks like you have found a manual backup guide, i.e. easy copying of data folders. If you made a backup in the control panel, then the backup file is stored at the path you specified. If it was a temporary backup, then it is deleted after 24 hours.
