### ISSUE TITLE
Remove one of the domain from multitenancy setup

### ISSUE THREAD

**Issue by Abraka** [ONLYOFFICE/CommunityServer#450]
How do I remove one of the domain from multitenancy setup? There is only edit button, but nothing like delete this portal/subdomain. Thx.

**Comment by Carazyda** [comment]
Hello @Abraka. You cannot delete a domain, only change it using the edit button. You can also delete the current portal in the portal settings /Management.aspx?type=15.

**Comment by Abraka** [comment]
Thx for reply. Are there any plans to incorporate better management of multitenancy setup into OO? Like better control over multiple domain setting, subdomain portals, their removal etc.

**Comment by Carazyda** [comment]
Sorry, but there are no such plans in the next releases.
