### ISSUE TITLE
Help center translation

### ISSUE THREAD

**Issue by GP3io** [ONLYOFFICE/CommunityServer#451]
Hello!
Please tell me how can I translate the help center documents inside CommuntyServer? I have the entire portal in Russian and only help in English.

**Comment by Carazyda** [comment]
Hello @GP3io Sorry, but this is not implemented yet. In future releases, we will add a change in the language of the built-in help center depending on the user's language (Bug 56093 in our private bugtracker). While you can use our https://helpcenter.onlyoffice.com/.

**Comment by GP3io** [comment]
Ok. Thank you
