### ISSUE TITLE
backup and restore to a new server

### ISSUE THREAD

**Issue by annibal1** [ONLYOFFICE/CommunityServer#458]
Hi everyone
I can't find a detailed guide to solve my doubt
I installed the onlyoffice-workspace version on a new server
using docker on ubuntu 20.04
now I would like to transfer the backup of the old server always with ubuntu 20.04 installed and docker with onlyoffice workspace to the new server
I read that I have to extrapolate the key but I have not found a detailed guide to do this
As soon as the backup and data transfer works, I change the domain and point it to the new server
is there any guide to follow to do this??

**Comment by Carazyda** [comment]
Hello @annibal1 You can read this [instruction](https://helpcenter.onlyoffice.com/administration/control-panel-backup.aspx), Restore section. You must perform the backup and restore process on the same versions of Onlyoffice components. You can also copy the /app folder to a new server and install Onlyoffice using docker with our script.

**Comment by annibal1** [comment]
hello thanks for your reply
I have a problem now
As soon as I click Restores, gives me error while recovering the data
do you know how I can solve?
thank you for your support

**Comment by Carazyda** [comment]
Are the versions of the Onlyoffice components the same, in which did you backup and try to restore? Also check svcBackup.log for errors.

**Comment by annibal1** [comment]
Attached is the log file
[svcBackup.log](https://github.com/ONLYOFFICE/CommunityServer/files/11180906/svcBackup.log)

**Comment by Carazyda** [comment]
I don't see any errors on the restore process. Please try to restore and then attach a new log file.

**Comment by annibal1** [comment]
Perfect thanks for your help
I understood how the backup works and restore
I also noticed that by changing the servers and putting the backup the very useful thing and that it did not change the code of the link so I had no discomfort
I ask if the integration of Access and Project is foreseen
Thank you so much for your job

**Comment by Carazyda** [comment]
Do you mean Microsoft Access? And what projects? Module Projects in ONLYOFFICE? Please describe your case in more detail.

**Comment by annibal1** [comment]
It would be very useful to work with Microsoft Access and Microsoft Project with OnlyOffice modules
I hope that in the future it can be integrated with OnlyOffice to work like this also with the programs described
For me who are a P.M (Project Manager) would be very useful to have integrated these 2 programs in Olyoffice but I think that many other users would also be very useful to be able to work Onlyne with the programs described

**Comment by Carazyda** [comment]
Sorry, but there are no plans for such integration in the near future. But we will think about it. Your problem is solved, can I close the issue?

**Comment by annibal1** [comment]
yes thanks
