### ISSUE TITLE
Mail Server domain setting is not displayed

### ISSUE THREAD

**Issue by annibal1** [ONLYOFFICE/CommunityServer#459]
HI
I am trying to insert my domain for the creation of emails but the creation button is not displayed or adding domain for the creation of the mailbox
Is there a particular procedure to perform?
I installed OnlyOffice Workspace on Docker
thanks for your collaboration

**Comment by Carazyda** [comment]
Hello @annibal1 Have you installed our mail server? You can check this on the Control Panel Update tab. After installing the mail server, you can configure it as in [instructions](https://helpcenter.onlyoffice.com/administration/mail-server.aspx).

**Comment by annibal1** [comment]
Yes
  it is installed
![Immagine 2023-04-08 183904](https://user-images.githubusercontent.com/50693441/230732813-1146d8fe-b104-461d-ba2e-8837fa5cf819.png)

**Comment by Carazyda** [comment]
And you don't have a Mail Server tab in the Mail module on your portal? Also check the connection in the portal settings on the Mail Server tab (/Management.aspx?type=20).

**Comment by annibal1** [comment]
At this address that you specified there is the mail server but I miss the form to add my mail domain
![Immagine 2023-04-08 185433](https://user-images.githubusercontent.com/50693441/230733507-a84920f2-0587-485f-99e4-2d875b543c0b.png)

**Comment by Carazyda** [comment]
How did you install Onlyoffice? what about Mail Server? You need to specify the ip of the mail server container in this field. You can find it with this command:
`docker inspect onlyoffice-mail-server -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}'`

**Comment by annibal1** [comment]
yes with this command you wrote it gives me a different IP
Which file I have to edit to put the IP of my server?
Thanks for your collaboration and patience

**Comment by Carazyda** [comment]
You need to specify this ip in the Mail server tab of the portal settings (/Management.aspx?type=20). Click Connect and if there are no errors, click Save. After that, the mail server should appear in the mail module.

**Comment by annibal1** [comment]
HI
I tried
but it gives me error as per the attached image

![Immagine 2023-04-09 095227](https://user-images.githubusercontent.com/50693441/230761090-e7fc6b8b-0daf-473f-a227-0c62a1d40cc2.png)

**Comment by Carazyda** [comment]
What host OS are you using? Please try restarting the mail server container - `docker restart onlyoffice-mail-server`. If that doesn't help, attach `docker logs onlyoffice-mail-server`.

**Comment by annibal1** [comment]
HI
I'm using Ubuntu 18.04
Even by restoring the Docker he did not help me to solve the problema
Attached is the required log file
[log onlyoffice mail.txt](https://github.com/ONLYOFFICE/CommunityServer/files/11185810/log.onlyoffice.mail.txt)

**Comment by Carazyda** [comment]
It looks like your mail server is not starting up completely. This is the entire output, nothing new in the output appeared?

**Comment by annibal1** [comment]
I performed a test by creating a new server and installing the OnlyOffice Workspace server
With clean installation I can add the domain to the email and create mailboxes without any problem
After I put the key to the old server in the new server, restarted the new server and installed a backup of the old server
When the portal has returned online, I no longer add/modify the domain for the creation of the email
and the problem described above is back
Do you have any ideas on how I could solve?
Thank you

**Comment by Carazyda** [comment]
After reinstallation, all your data will be saved in the /app/ folder. Or do you do the recovery many times?

**Comment by annibal1** [comment]
just 1 time only

**Comment by Carazyda** [comment]
Then you can use the option to reinstall containers. You need to remove the containers and run the setup script with your parameters.
`sudo docker rm -f $(sudo docker ps -aq)`
`bash workspace-install.sh -(your parameters)`

**Comment by Carazyda** [comment]
No, I mean how did you do it? Are you providing the -mk parameter to our script? Or do you change it in the /app/onlyoffice/CommunityServer/data/.private folder? Or change it in the config files to the server community container?

Based on your error, the MySQL container does not start. Also provide `docker logs onlyoffice-mysql-server`.

**Comment by annibal1** [comment]
no
I installed the new server
Then I backup of the old server of the whole folder /app and their respective ones under folders and that is CommunityServer Documentserver Controlpanel etc. then also the Machinekey and put everything in the new server
after I restarted the server
Logs OnlyOffice-Mysql-Server are also attached
Thank you for your patience to try to solve my problem

l'
2023-04-13 18:40:00+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.29-1.el8 started.
'/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
2023-04-13 18:41:03+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.29-1.el8 started.

**Comment by Carazyda** [comment]
Is this the whole mysql container log? It seems that some lines are missing. Have you changed your MySQL connection settings? Also try first copying the /app/ folder from the old server to the new server and then running our installation script.

**Comment by annibal1** [comment]
The update fixed the problem
