### ISSUE TITLE
can't work with Mysql5.6+

### ISSUE THREAD

**Issue by renothing** [ONLYOFFICE/CommunityServer#46]
I have run communityserver by docker, 

> ENV:
> version: onlyoffice/communityserver:8.9.1.191

when I use extral database mysql5.6 outside docker, the document module will not work.

Error:

> When @@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1, the statements CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE can be executed in a non-transactional context only, and require that AUTOCOMMIT = 1. These statements are also not allowed in a function or trigger because functions and triggers are also considered to be multi-statement transactions.

but the mysql replication based gtid is recommended by mysql official, also most 5.6 users works on this mode.

is there anyway to avolid it ?

**Comment by JohnPerkin** [comment]
Hello!
Disable scrict mode in MySQL with the following command
`echo "sql_mode = 'NO_ENGINE_SUBSTITUTION'" >> /etc/mysql/mysql.conf.d/mysqld.cnf`
Then the installation should succeed.
