### ISSUE TITLE
unused fields

### ISSUE THREAD

**Issue by dslengel** [ONLYOFFICE/CommunityServer#462]
Hello together,

I use the Community Server 12.1.1194. 
There are a lot of unused fields in it. My question is whether and how I can eliminate these many fields:
For example: 
Skype (privat)	Skype (geschäftlich)	Skype (sonstiges)	Twitter (privat)	Twitter (geschäftlich)	Twitter (sonstiges)	... and many, many more.

I look forward to hearing from you again.

**Comment by dslengel** [comment]
Hi @Carazyda
Yes, it is the CRM.
When I export my data, there are always many columns in the file that I don't need. Therefore I wanted to know from you if it is possible to delete these (for me) unnecessary columns. Maybe in MySQL?
With the goal that they no longer appear as columns to be exported.

Do you know what I mean?
I have marked the columns in the example as "unneccessary"

<HTML>
<HEAD>
	
	<META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=utf-8">
	<TITLE></TITLE>
	<META NAME="GENERATOR" CONTENT="OpenOffice 4.1.13  (Win32)">
	<STYLE>
		
	</STYLE>
	
</HEAD>

<BODY TEXT="#000000">
<TABLE FRAME=VOID CELLSPACING=0 COLS=93 RULES=NONE BORDER=0>
	<COLGROUP><COL WIDTH=140><COL WIDTH=66><COL WIDTH=77><COL WIDTH=166><COL WIDTH=61><COL WIDTH=59><COL WIDTH=162><COL WIDTH=78><COL WIDTH=236><COL WIDTH=119><COL WIDTH=101><COL WIDTH=100><COL WIDTH=97><COL WIDTH=101><COL WIDTH=126><COL WIDTH=98><COL WIDTH=135><COL WIDTH=122><COL WIDTH=106><COL WIDTH=147><COL WIDTH=133><COL WIDTH=97><COL WIDTH=135><COL WIDTH=122><COL WIDTH=97><COL WIDTH=137><COL WIDTH=123><COL WIDTH=106><COL WIDTH=147><COL WIDTH=133><COL WIDTH=116><COL WIDTH=156><COL WIDTH=143><COL WIDTH=175><COL WIDTH=166><COL WIDTH=205><COL WIDTH=153><COL WIDTH=161><COL WIDTH=169><COL WIDTH=160><COL WIDTH=198><COL WIDTH=147><COL WIDTH=154><COL WIDTH=150><COL WIDTH=141><COL WIDTH=180><COL WIDTH=128><COL WIDTH=135><COL WIDTH=189><COL WIDTH=180><COL WIDTH=218><COL WIDTH=167><COL WIDTH=174><COL WIDTH=177><COL WIDTH=168><COL WIDTH=207><COL WIDTH=155><COL WIDTH=163><COL WIDTH=151><COL WIDTH=142><COL WIDTH=181><COL WIDTH=129><COL WIDTH=137><COL WIDTH=122><COL WIDTH=163><COL WIDTH=149><COL WIDTH=113><COL WIDTH=154><COL WIDTH=141><COL WIDTH=97><COL WIDTH=132><COL WIDTH=119><COL WIDTH=102><COL WIDTH=143><COL WIDTH=129><COL WIDTH=97><COL WIDTH=135><COL WIDTH=122><COL WIDTH=97><COL WIDTH=127><COL WIDTH=113><COL WIDTH=97><COL WIDTH=120><COL WIDTH=106><COL WIDTH=97><COL WIDTH=137><COL WIDTH=123><COL WIDTH=97><COL WIDTH=121><COL WIDTH=107><COL WIDTH=97><COL WIDTH=116><COL WIDTH=102></COLGROUP>
	<TBODY>
		<TR>
			<TD WIDTH=140 HEIGHT=17 ALIGN=LEFT>Unternehmen/Person</TD>
			<TD WIDTH=66 ALIGN=LEFT>Vorname</TD>
			<TD WIDTH=77 ALIGN=LEFT>Nachname</TD>
			<TD WIDTH=166 ALIGN=LEFT>Name des Unternehmens</TD>
			<TD WIDTH=61 ALIGN=LEFT>Position</TD>
			<TD WIDTH=59 ALIGN=LEFT>Hinweis</TD>
			<TD WIDTH=162 ALIGN=LEFT>Kontakttemperaturniveau</TD>
			<TD WIDTH=78 ALIGN=LEFT>Kontakttyp</TD>
			<TD WIDTH=236 ALIGN=LEFT>Liste mit Schlagwörtern der Kontakte</TD>
			<TD WIDTH=119 ALIGN=LEFT>Telefon (zuhause)</TD>
			<TD WIDTH=101 ALIGN=LEFT>Telefon (arbeit)</TD>
			<TD WIDTH=100 ALIGN=LEFT>Telefon (mobil)</TD>
			<TD WIDTH=97 ALIGN=LEFT>Telefon (fax)</TD>
			<TD WIDTH=101 ALIGN=LEFT>Telefon (direkt)</TD>
			<TD WIDTH=126 ALIGN=LEFT>Telefon (sonstiges)</TD>
			<TD WIDTH=98 ALIGN=LEFT>E-Mail (privat)</TD>
			<TD WIDTH=135 ALIGN=LEFT>E-Mail (geschäftlich)</TD>
			<TD WIDTH=122 ALIGN=LEFT>E-Mail (sonstiges)</TD>
			<TD WIDTH=106 ALIGN=LEFT>Website (privat)</TD>
			<TD WIDTH=147 ALIGN=LEFT>Website (geschäftlich)</TD>
			<TD WIDTH=133 ALIGN=LEFT>Website (sonstiges)</TD>
			<TD WIDTH=97 ALIGN=LEFT>Skype (privat)</TD>
			<TD WIDTH=135 ALIGN=LEFT>Skype (geschäftlich)</TD>
			<TD WIDTH=122 ALIGN=LEFT>Skype (sonstiges)</TD>
			<TD WIDTH=97 ALIGN=LEFT>Twitter (privat)</TD>
			<TD WIDTH=137 ALIGN=LEFT>Twitter (geschäftlich)</TD>
			<TD WIDTH=123 ALIGN=LEFT>Twitter (sonstiges)</TD>
			<TD WIDTH=106 ALIGN=LEFT>LinkedIn (privat)</TD>
			<TD WIDTH=147 ALIGN=LEFT>LinkedIn (geschäftlich)</TD>
			<TD WIDTH=133 ALIGN=LEFT>LinkedIn (sonstiges)</TD>
			<TD WIDTH=116 ALIGN=LEFT>Facebook (privat)</TD>
			<TD WIDTH=156 ALIGN=LEFT>Facebook (geschäftlich)</TD>
			<TD WIDTH=143 ALIGN=LEFT>Facebook (sonstiges)</TD>
			<TD WIDTH=175 ALIGN=LEFT>Adresse (startseite) straße</TD>
			<TD WIDTH=166 ALIGN=LEFT>Adresse (startseite) stadt</TD>
			<TD WIDTH=205 ALIGN=LEFT>Adresse (startseite) bundesland</TD>
			<TD WIDTH=153 ALIGN=LEFT>Adresse (startseite) plz</TD>
			<TD WIDTH=161 ALIGN=LEFT>Adresse (startseite) land</TD>
			<TD WIDTH=169 ALIGN=LEFT>Adresse (lieferung) straße</TD>
			<TD WIDTH=160 ALIGN=LEFT>Adresse (lieferung) stadt</TD>
			<TD WIDTH=198 ALIGN=LEFT>Adresse (lieferung) bundesland</TD>
			<TD WIDTH=147 ALIGN=LEFT>Adresse (lieferung) plz</TD>
			<TD WIDTH=154 ALIGN=LEFT>Adresse (lieferung) land</TD>
			<TD WIDTH=150 ALIGN=LEFT>Adresse (office) straße</TD>
			<TD WIDTH=141 ALIGN=LEFT>Adresse (office) stadt</TD>
			<TD WIDTH=180 ALIGN=LEFT>Adresse (office) bundesland</TD>
			<TD WIDTH=128 ALIGN=LEFT>Adresse (office) plz</TD>
			<TD WIDTH=135 ALIGN=LEFT>Adresse (office) land</TD>
			<TD WIDTH=189 ALIGN=LEFT>Adresse (fakturierung) straße</TD>
			<TD WIDTH=180 ALIGN=LEFT>Adresse (fakturierung) stadt</TD>
			<TD WIDTH=218 ALIGN=LEFT>Adresse (fakturierung) bundesland</TD>
			<TD WIDTH=167 ALIGN=LEFT>Adresse (fakturierung) plz</TD>
			<TD WIDTH=174 ALIGN=LEFT>Adresse (fakturierung) land</TD>
			<TD WIDTH=177 ALIGN=LEFT>Adresse (sonstiges) straße</TD>
			<TD WIDTH=168 ALIGN=LEFT>Adresse (sonstiges) stadt</TD>
			<TD WIDTH=207 ALIGN=LEFT>Adresse (sonstiges) bundesland</TD>
			<TD WIDTH=155 ALIGN=LEFT>Adresse (sonstiges) plz</TD>
			<TD WIDTH=163 ALIGN=LEFT>Adresse (sonstiges) land</TD>
			<TD WIDTH=151 ALIGN=LEFT>Adresse (stelle) straße</TD>
			<TD WIDTH=142 ALIGN=LEFT>Adresse (stelle) stadt</TD>
			<TD WIDTH=181 ALIGN=LEFT>Adresse (stelle) bundesland</TD>
			<TD WIDTH=129 ALIGN=LEFT>Adresse (stelle) plz</TD>
			<TD WIDTH=137 ALIGN=LEFT>Adresse (stelle) land</TD>
			<TD WIDTH=122 ALIGN=LEFT>LiveJournal (privat)</TD>
			<TD WIDTH=163 ALIGN=LEFT>LiveJournal (geschäftlich)</TD>
			<TD WIDTH=149 ALIGN=LEFT>LiveJournal (sonstiges)</TD>
			<TD WIDTH=113 ALIGN=LEFT>MySpace (privat)</TD>
			<TD WIDTH=154 ALIGN=LEFT>MySpace (geschäftlich)</TD>
			<TD WIDTH=141 ALIGN=LEFT>MySpace (sonstiges)</TD>
			<TD WIDTH=97 ALIGN=LEFT>Gmail (privat)</TD>
			<TD WIDTH=132 ALIGN=LEFT>Gmail (geschäftlich)</TD>
			<TD WIDTH=119 ALIGN=LEFT>Gmail (sonstiges)</TD>
			<TD WIDTH=102 ALIGN=LEFT>Blogger (privat)</TD>
			<TD WIDTH=143 ALIGN=LEFT>Blogger (geschäftlich)</TD>
			<TD WIDTH=129 ALIGN=LEFT>Blogger (sonstiges)</TD>
			<TD WIDTH=97 ALIGN=LEFT>Yahoo (privat)</TD>
			<TD WIDTH=135 ALIGN=LEFT>Yahoo (geschäftlich)</TD>
			<TD WIDTH=122 ALIGN=LEFT>Yahoo (sonstiges)</TD>
			<TD WIDTH=97 ALIGN=LEFT>MSN (privat)</TD>
			<TD WIDTH=127 ALIGN=LEFT>MSN (geschäftlich)</TD>
			<TD WIDTH=113 ALIGN=LEFT>MSN (sonstiges)</TD>
			<TD WIDTH=97 ALIGN=LEFT>ICQ (privat)</TD>
			<TD WIDTH=120 ALIGN=LEFT>ICQ (geschäftlich)</TD>
			<TD WIDTH=106 ALIGN=LEFT>ICQ (sonstiges)</TD>
			<TD WIDTH=97 ALIGN=LEFT>Jabber (privat)</TD>
			<TD WIDTH=137 ALIGN=LEFT>Jabber (geschäftlich)</TD>
			<TD WIDTH=123 ALIGN=LEFT>Jabber (sonstiges)</TD>
			<TD WIDTH=97 ALIGN=LEFT>AIM (privat)</TD>
			<TD WIDTH=121 ALIGN=LEFT>AIM (geschäftlich)</TD>
			<TD WIDTH=107 ALIGN=LEFT>AIM (sonstiges)</TD>
			<TD WIDTH=97 ALIGN=LEFT>VK (privat)</TD>
			<TD WIDTH=116 ALIGN=LEFT>VK (geschäftlich)</TD>
			<TD WIDTH=102 ALIGN=LEFT>VK (sonstiges)</TD>
		</TR>
		<TR>
			<TD HEIGHT=18 ALIGN=LEFT>Person</TD>
			<TD ALIGN=LEFT>Test</TD>
			<TD ALIGN=LEFT>Tester</TD>
			<TD ALIGN=LEFT>Test-Company</TD>
			<TD ALIGN=LEFT>GF</TD>
			<TD ALIGN=LEFT>Test</TD>
			<TD ALIGN=LEFT>nicht erreicht</TD>
			<TD ALIGN=LEFT>Kunde</TD>
			<TD ALIGN=LEFT>test</TD>
			<TD ALIGN=LEFT>xxx-xxxxxx</TD>
			<TD ALIGN=LEFT>xxx-xxxxxx</TD>
			<TD ALIGN=LEFT>xxxx-xxxxxx</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>test1@test.de</TD>
			<TD ALIGN=LEFT>test2@test.de</TD>
			<TD ALIGN=LEFT>test3@test.de</TD>
			<TD ALIGN=LEFT>www.www.de</TD>
			<TD ALIGN=LEFT>www.www2.de</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>Test Str. 173</TD>
			<TD ALIGN=LEFT>Stadt</TD>
			<TD ALIGN=LEFT>Land</TD>
			<TD ALIGN=LEFT>xxxxx</TD>
			<TD ALIGN=LEFT>DE</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
			<TD ALIGN=LEFT>unneccessary</TD>
		</TR>
	</TBODY>
</TABLE>
</BODY>

</HTML>

**Comment by Carazyda** [comment]
Sorry, but this can only be done in source codes and recompiled with changes. There is no way to fix this through the database.

**Comment by dslengel** [comment]
Well, then. Too bad there's no other way. 
It's a pity to have to deal with quite a few columns that are completely unnecessary
