### ISSUE TITLE
Can not detect the current version in control panel when update

### ISSUE THREAD

**Issue by gamekingv** [ONLYOFFICE/CommunityServer#463]
Hi, I found the hint "Unfortunately we could not detect the current version of ONLYOFFICE products installed." in control panel when I want to check if I can update. And it says that possibly because the docker version it's too old. The docker version on my host it's 20.10.21. Is it the version onlyoffice doesn't fully support?

**Comment by Carazyda** [comment]
Hello @gamekingv it looks like the problem is not with the docker version. Can you attach the control panel logs (/app/onlyoffice/ControlPanel/logs)? And the output of `docker ps`?

**Comment by gamekingv** [comment]
> Hello @gamekingv it looks like the problem is not with the docker version. Can you attach the control panel logs (/app/onlyoffice/ControlPanel/logs)? And the output of `docker ps`?

cat web.controlpanel.04-26.log 
2023-04-26 07:09:33 - error: executeOneClickinstallScript stderr
2023-04-26 07:09:33 - error: Error: No such object: onlyoffice-mail-server

2023-04-26 07:24:53 - error: executeOneClickinstallScript stderr
2023-04-26 07:24:53 - error: Error: No such object: onlyoffice-mail-server

2023-04-26 07:44:33 - error: executeOneClickinstallScript stderr
2023-04-26 07:44:33 - error: Error: No such object: onlyoffice-mail-server

2023-04-26 07:59:41 - error: executeOneClickinstallScript stderr
2023-04-26 07:59:41 - error: Error: No such object: onlyoffice-mail-server

docker ps
CONTAINER ID   IMAGE                        COMMAND                  CREATED        STATUS        PORTS                                                                                                                                                                                  NAMES
8d0124201ba1   onlyoffice/documentserver    "/app/ds/run-documen…"   4 months ago   Up 2 months   80/tcp, 443/tcp                                                                                                                                                                        onlyoffice-document-server
2188304bc60b   onlyoffice/communityserver   "/app/run-community-…"   4 months ago   Up 2 months   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 3306/tcp, 5280/tcp, 9865-9866/tcp, 9871/tcp, 9882/tcp, 0.0.0.0:5222->5222/tcp, :::5222->5222/tcp, 9888/tcp   onlyoffice-community-server
9c4acff8e5a4   onlyoffice/controlpanel      "/var/www/onlyoffice…"   4 months ago   Up 2 months   80/tcp, 443/tcp                                                                                                                                                                        onlyoffice-control-panel
b98df18cbdf8   mysql:5.7                    "docker-entrypoint.s…"   4 months ago   Up 2 months   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp                                                                                                                                   onlyoffice-mysql-server

**Comment by Carazyda** [comment]
How did you install Onlyoffice Workspace? Your docker images don't have a version tag.

**Comment by gamekingv** [comment]
I just follow this [Installation guides](https://helpcenter.onlyoffice.com/installation/workspace-install-docker-integrated.aspx) because I don't need the mail component.

**Comment by gamekingv** [comment]
Thank you. I'll try it.
