### ISSUE TITLE
How to completely disable internet access for WorkSpace and Docs?

### ISSUE THREAD

**Issue by dwpoint** [ONLYOFFICE/CommunityServer#466]
Hello. I installed the excellent OnlyOffice SpaceWork program on a local Windows 2016 x86 server. Also before that I installed OnlyOffice Docs.

Tell me, is it possible to somehow completely disable Internet access for all OnlyOffice components? I would very much like OnlyOffice not to collect any information and it is especially important that the documents do not end up on the network.

I tried to disable in the firewall:
1. ONLYOFFICE DocumentServer Proxy Service
2. ONLYOFFICE Jabber
3. ONLYOFFICE Mail

But when registering in WorkSpace, I still received an e-mail to confirm my account.

I would like to block internet access so that WorkSpace can't even send emails.

Is it possible?

That is, I would like to completely disable the possibility of any OnlyOffice connection to the Internet, both for OnlyOffice Docs and OnlyOffice WorkSpace.

**Comment by Carazyda** [comment]
Hello @dwpoint. By default, Onlyoffice Workspace uses notify.onlyoffice.info as the smtp server. If you disable your internet connection, you should set up a local smtp server for notifications.

Onlyoffice Workspace includes Onlyoffice Docs and you don't need to install it again before or after installing the workspace.

**Comment by dwpoint** [comment]
@Carazyda It's just that for my task I don't need access to the Internet at all. Do you understand?
My task is only to co-edit the document. I want to allow access to the workspace to everyone who is on the local network.

I don't want to use smtp at all, you know? And I don't want to use the mail itself either. She is not needed.

Tell me, can I somehow disable Internet access for WorkSpace? So that no updates come, no notifications, etc.
Do you understand what I mean?

**Comment by Carazyda** [comment]
In this case, just turn off the Internet on the server where Onlyoffice is installed.

**Comment by dwpoint** [comment]
@Carazyda Unfortunately, I can't do that because other programs need to work with the internet. For example, parsing through Python

**Comment by Carazyda** [comment]
If you need to block access to the Internet only for certain programs, you can set up rules in Windows Defender Firewall. List of ports used by [Onlyoffice Docs](https://helpcenter.onlyoffice.com/installation/docs-community-open-ports.aspx) and [Onlyoffice Groups](https://helpcenter.onlyoffice.com/installation/groups-open-ports.aspx).

**Comment by dwpoint** [comment]
@Carazyda And how to find out which ports are used for these programs to block?

**Comment by Carazyda** [comment]
I have attached links to our help center with a list of ports in the comment above.

> List of ports used by [Onlyoffice Docs](https://helpcenter.onlyoffice.com/installation/docs-community-open-ports.aspx) and [Onlyoffice Groups](https://helpcenter.onlyoffice.com/installation/groups-open-ports.aspx).

**Comment by dwpoint** [comment]
@Carazyda Thank you. And tell me, if I block these ports, will WorkSpace be available through the browser as a local website?

**Comment by Carazyda** [comment]
Yes, if you block them for internet traffic only.
