### ISSUE TITLE
Is it possible to set the default co-editing mode to "Strict"?

### ISSUE THREAD

**Issue by dwpoint** [ONLYOFFICE/CommunityServer#467]
Hello. I am creating an excel document in SpaceWork. I have set the editing mode to Strict. I save. I give access to other people, and after that, when they go to the document, they still have the co-editing mode set to "Quick" by default. And they have to manually change it.

My question is related to whether it is possible to make it so that when other people open the document, the co-editing mode is exactly what I specify? Or is it impossible?

I need to set the co-editing mode to "Strict" for all documents. Maybe in the configuration files it is possible to change this function by default?

**Comment by Carazyda** [comment]
Hello @dwpoint Sorry, but unfortunately there is no such setting in the server configuration now. The co-editing mode value is stored on the client. We will consider and possibly add this setting.

**Comment by dwpoint** [comment]
@Carazyda А есть ли возможность сейчас у меня через файлы в директориях C:\Program Files (x86)\Ascensio System SIA\ сделать это самому?

**Comment by Carazyda** [comment]
No, unfortunately this is currently not possible.
