### ISSUE TITLE
Is it possible to hide "Feed" just like "People", "CRM", "Projects", etc.?

### ISSUE THREAD

**Issue by dwpoint** [ONLYOFFICE/CommunityServer#471]
Hello everyone. I am using Workspace. I have configured the navigation panel and hidden all the items. But the "Feed" remains by default. There is no checkbox for it. Is it possible to hide it somehow, by accessing the source code, for example?

**Comment by Carazyda** [comment]
Hello @dwpoint Sorry, but this option is not available right now. There is a suggestion for the ability to disable the module Feed (a bug 55710 in our internal bugtracker).
