### ISSUE TITLE
Install Debian 12.1.0 aborts with the following error

### ISSUE THREAD

**Issue by judie07** [ONLYOFFICE/CommunityServer#477]
Hy, the installation ONLYOFFICE Workspace with DEB-Packeten on Debian 12.1.0 aborts with the following error message:

`wget https://download.onlyoffice.com/install/install-Debian.sh`
`bash install-Debian.sh -it WORKSPACE`

`Err:16 https://download.mono-project.com/repo/debian stable-bookworm/snapshots/6.8.0.123 Release
  404  Not Found [IP: 2606:2800:133:206e:1315:22a5:2006:24fd 443]
Get:17 https://d2nlctn12v279m.cloudfront.net/repo/mono/ubuntu xenial/main amd64 Packages [602 B]
....
Get:22 https://packages.microsoft.com/debian/12/prod bookworm/main arm64 Packages [2331 B]
Reading package lists... Done
E: The repository 'https://download.mono-project.com/repo/debian stable-bookworm/snapshots/6.8.0.123 Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

The installation under Debian 11.6.0 works

**Comment by Carazyda** [comment]
Hello @judie07 Yes, we are aware of this issue. We will fix this soon.

**Comment by Tragen** [comment]
Do you have a time frame for the fix?
3 weeks is not soon for me.

**Comment by Carazyda** [comment]
Sorry for the late reply. The fix is already in the release. You can try installing Onlyoffice Workspace on Debian 12 using our script.

**Comment by Tragen** [comment]
I've it already running on Debian 11 and the upgrade failed because of OO.
Now I can try again. Thanks.
