### ISSUE TITLE
Missing tables during install

### ISSUE THREAD

**Issue by logicexpertise** [ONLYOFFICE/CommunityServer#48]
When installing Community Server (following the instructions at http://helpcenter.onlyoffice.com/server/linux/community/linux-installation.aspx#InstallingRHEL and running the script at /var/www/onlyoffice/configure.sh) the following errors are displayed:

```
ERROR 1146 (42S02) at line 224: Table '[database-name].wiki_pages' doesn't exist
ERROR 1146 (42S02) at line 78: Table '[database-name].tenants_quota' doesn't exist
ERROR 1146 (42S02) at line 27: Table '[database-name].tenants_partners' doesn't exist
ERROR 1146 (42S02) at line 87: Table '[database-name].res_files' doesn't exist
```

This causes a MySql.Data.MySqlClinet.MySqlException exception when loading the application in the web browser.

**Comment by tosigus** [comment]
Same problem on Ubuntu 16.04.

**Comment by ibnpetr** [comment]
Hello
I regret to inform you that there is an issue with MySQL 5.7, we are working on it.
We will keep you updated on the progress.
Best regards

**Comment by JohnPerkin** [comment]
Hello!
Current version of ONLYOFFICE supports MySQL 5.7. The only detail is that you have to specify a password during the MySQL installation process.
Best regards
ONLYOFFICE support team

**Comment by JohnPerkin** [comment]
Hello!
Also you may disable scrict mode in MySQL with the following command
echo "sql_mode = 'NO_ENGINE_SUBSTITUTION'" >> /etc/mysql/mysql.conf.d/mysqld.cnf
Then the installation should succeed.
