### ISSUE TITLE
How to integrate Only Office with Keycloak using openId connect 

### ISSUE THREAD

**Issue by prajwalpgood** [ONLYOFFICE/CommunityServer#484]
I want to integrate Only Office with Keycloak using OpenID connect. but the link provide supports SAML standard https://helpcenter.onlyoffice.com/administration/control-panel-sso-description.aspx, I want to know OnlyOffice support OpenId connect, if yes please provide document that explains in detail.

**Comment by Carazyda** [comment]
Hello @prajwalpgood Sorry, but we don't have official support or documentation for this. You can check this issue https://github.com/ONLYOFFICE/CommunityServer/issues/470, some users managed to connect keycloak.
