### ISSUE TITLE
Task comments not deleted

### ISSUE THREAD

**Issue by GabrieleCarabella** [ONLYOFFICE/CommunityServer#49]
When you delete a project the comments related to the tasks are not deleted.

**Comment by JohnPerkin** [comment]
Hello!
Please describe the issue in details and attach screenshots of it. Comments have to be deleted together with projects so this is not a normal scenario.

**Comment by JohnPerkin** [comment]
Hello @GabrieleCarabella !
The problem with deleting tasks together with their comments is fixed in Community Server 9.0 which soon will be released. We will inform you about its releasing in our [Changelog](https://github.com/ONLYOFFICE/CommunityServer/releases).
