### ISSUE TITLE
Error "An item with the same key has already been added" occurs when mark files as read.

### ISSUE THREAD

**Issue by esri-auto** [ONLYOFFICE/CommunityServer#495]
Steps:

1. Upload some folder with files to the Common folder(Include some duplicated files in different folders. e.g. `path1_to/img1.jpg`, `path2_to/img1.jpg`, etc)
2. Swith to another user. You will see the number of new files.
3. Try to click the number to mark all files as read.

Actual result:
Error message displays for the duplicated files. please see screenshot below:
![mark as read](https://github.com/ONLYOFFICE/CommunityServer/assets/88422894/4d589b48-34c3-409d-b721-66a5f615c162)

Additional info:
This issue may not be 100% reproducible. I tried with only a few folders and files(e.g. `test/folder1/1.jpg`, `test/folder2/1.jpg`) and it works well.

Environment:
Community Edition, Docker version

**Comment by Carazyda** [comment]
Hello @esri-auto. We will fix this issue in version 12.6.0, which will be released soon. For now, you can temporarily resolve this by `truncate files_tag_link` table in the database.

**Comment by esri-auto** [comment]
Yes the truncate command works. Thanks.
