### ISSUE TITLE
ONLYOFFICE UrlShortener service does not work if the external database does not use port 3306

### ISSUE THREAD

**Issue by ydelattre** [ONLYOFFICE/CommunityServer#497]
Hello.

A few weeks ago, we migrated our MySQL database. Now the new database uses 3318 port instead of the default MySQL port 3306. Since then, the ONLYOFFICE UrlShortener Service no longer works.
Indeed, the port is not specified in config.json of this service :

root@a757e4c704ce:/var/www/onlyoffice/Services/ASC.UrlShortener/config# cat config.UNIX.SERVER.json
{
"port": 9999,
"core.machinekey": "XXXXXXXXXXXXXXXXXXXXX",
"logPath": "/var/log/onlyoffice/web.urlshortener.log",
"sql": {
"host": "mybdd_hostname",
"user": "mybdd_user",
"password": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
"database": "mybdd_database"
}

Adding it, solved the problem.

FYI :
- Installation on Docker 25.0.3
- OnlyOffice Groups 12.5.2.1848

Thanks.
Regards.
Yoann.

**Comment by andreysavihin** [comment]
Hi @ydelattre!
Try manually adding "port": 3318 to the config file in the sql section and restarting the service.

**Comment by ydelattre** [comment]
Hi @andreysavihin

Thanks for your answer.
Indeed, adding it fixed the problem until the next container restart...
Could you, please, make a change to the entrypoint script to be able to use a custom database port with ONLYOFFICE UrlShortener service ?

Thanks a lot.
Yoann

**Comment by andreysavihin** [comment]
We will fix it in the next release
