### ISSUE TITLE
Project document directory not created

### ISSUE THREAD

**Issue by GabrieleCarabella** [ONLYOFFICE/CommunityServer#50]
When an user with projects privelege create a new project, the document directory of project is not created.  To solve this problem you must also enable the privilege for documents.

**Comment by ibnpetr** [comment]
Hello 
I regret to inform you that we cannot reproduce the issue. Could you please send us more information about the environment (os, product version, installation type) and describe your actions step by step.
It also would be great if you make step by step description with screenshots and send it to support@onlyoffice.com (subj - github)
