### ISSUE TITLE
Can I get all the comments on the tasks in one request?

### ISSUE THREAD

**Issue by geloidA** [ONLYOFFICE/CommunityServer#504]
Hi! Is it possible to get all the comments on a project's tasks with a single API request?

**Comment by Carazyda** [comment]
Hello @geloidA You can use this method https://api.onlyoffice.com/portals/method/project/get/api/2.0/project/task/%7btaskid%7d/comment. 

Or do you need to get comments in all tasks in all projects with one request?

**Comment by geloidA** [comment]
How i can understand method that you are mentioned allows get all comments for specific task in project, but i need get all tasks's comments in a project in a single JSON response. Or am i wrong?

**Comment by geloidA** [comment]
Thank you for your response.
