### ISSUE TITLE
installing via install-Debian.sh fails

### ISSUE THREAD

**Issue by dsl400** [ONLYOFFICE/CommunityServer#505]
installing via install-Debian.sh fails 
the installation script  checks for all ports to be closed then it fails because postgresql is not running

```
source install-Debian/tools.sh
source install-Debian/check-ports.sh
source install-Debian/install-preq.sh
systemctl start postgresql # <<<<<<<< inserting this line saved the day
source install-Debian/install-app.sh
```

**Comment by Carazyda** [comment]
Hello @dsl400 Please describe in more detail:
1) What OS are you using?
2) Is this a clean system?
3) Do you have Postgresql pre-installed or is it installed using our script?

**Comment by dsl400** [comment]
Postgres exists and it is stopped.
If I start it before running install-Debian.sh the script fails at check for ports
If I do not start postgres, the script fails at postgres is not running inside install-app.sh

**Comment by Carazyda** [comment]
Did you need this postgresql? Can you remove it and start the installation again with our script?
