### ISSUE TITLE
User auto activation

### ISSUE THREAD

**Issue by rapososoftwares** [ONLYOFFICE/CommunityServer#510]
Any way to enable auto activation of users that was synchronized with LDAP?

**Comment by Carazyda** [comment]
> auto activation

Hello @rapososoftwares What do you mean? Are you having trouble logging in or receiving email notifications?

**Comment by rapososoftwares** [comment]
> > auto activation
> 
> Hello @rapososoftwares What do you mean? Are you having trouble logging in or receiving email notifications?


I would like to disable the need of activate the user account by confirming by email.

**Comment by rapososoftwares** [comment]
.

**Comment by rapososoftwares** [comment]
I would like to disable the need to activate the user account by confirming by email.
