### ISSUE TITLE
Help unable to connect to caldav 

### ISSUE THREAD

**Issue by jhemley** [ONLYOFFICE/CommunityServer#512]
I have spent the last 4 hours attempting to login to caldav from my phone i have tried to login from the browser as well i believe the caldav service is running but i am unable to login there is a possibility i am just doing it wrong but any assistance would be greatly appreciated.

**Comment by Carazyda** [comment]
Hello @jhemley Please describe in more detail. What system do you have, how did you install Onlyoffice? How and where are you trying to connect CalDav?

**Comment by jhemley** [comment]
i am running the docker of onlyoffice community server 12.6.0.1900 on a esxi vm. I am trying to use the calendar on my iphone so i attempted to follow the guides but i just a verification failure. under username i have tried the user i use to login which is hemley.jared@gmail.com and for password i use the one i use to login as well. i have also tried under the user section hemley.jared@gmail.com@office.jaredhemley.com   to no avail still the verification failure.

**Comment by jhemley** [comment]
turns out the issue was that i had the option custom domain name enabled
