### ISSUE TITLE
Mail Module Not Working  

### ISSUE THREAD

**Issue by sach55** [ONLYOFFICE/CommunityServer#52]
I am using Windows 8.1,My SQL 5.7.14,Microsoft Windows Server 2012,Microsoft .NET Framework 4.5,IIS 8,Visual Studio 2012 
When I Send Mail It's show Me "**Images Are disable**".I  checked  Smtp Setting.it's  Working fine.And Other Module Like Create Project,Task etc. Are Working.
How Can I Fix This Issue This Error?

**Comment by AlexeySafronov** [comment]
Are you read this [instruction ](http://helpcenter.onlyoffice.com/server/windows/community/compile-source-code.aspx) to compile source? 

You may need to run some [script](https://github.com/ONLYOFFICE/CommunityServer/tree/master/build/sql) to update the database for current version.

**Comment by sach55** [comment]
Thanks,For Replay 
Yes,I Read The Instruction And Once I got The Mail In Inbox.And Then After Remove It And Re-Enter Same  Mail Id.
& I Also Add Updated Script.
Can I Use  Same Account For **Smtp Setting**  And **MailBox**(For Sending And Receiving Mail ) ?

**Comment by AlexeySafronov** [comment]
Yes, you can use same account for sending/receiving mail. You could test all our features in trial [Cloud version](https://www.onlyoffice.com/registration.aspx) or read the [instruction.](http://helpcenter.onlyoffice.com/mail.aspx)

**Comment by sergey-dryabzhinsky** [comment]
>> My SQL 5.7.14
This could trigger the issue. Maybe.
As mentioned in documentation - supported version is 5.5.
