### ISSUE TITLE
API returns 502 after unplanned power outage

### ISSUE THREAD

**Issue by ldwnt** [ONLYOFFICE/CommunityServer#521]
The workspace community was installed via script in this guide: https://helpcenter.onlyoffice.com/installation/docspace-community-install-script.aspx on a Ubuntu server 20.04 vm. After the power outage, the vm was restarted but the web UI was stucked and its API returned 502 bad gateway. The top command showed high cpu usage for these processes:
ASC.Files.Service.dll
ASC.Data.Backup.backgroundTasks.dll
ASC.Notify.dll
ASC.Studio.Notify.dll
ASC.Web.HealthChecks.UI.dll
What's the problem here and how do I fix it? Or can I export the docs from the VM if it's easier?

**Comment by Carazyda** [comment]
Hello @ldwnt, please indicate the status of monoserve?
`systemctl status monoserve`

And how much RAM and CPU does your VM have?

**Comment by ldwnt** [comment]
> Hello @ldwnt, please indicate the status of monoserve? `systemctl status monoserve`
> 
> And how much RAM and CPU does your VM have?

It says monoserve could not be found and "ps -ef|grep -i mono" also returns empty results. I look into the services and find some failed:
DocSpace-api-system
DocSpace-api (failed)
DocSpace-backup-background (start)
DocSpace-backup
DocSpace-clear-events
DocSpace-doceditor
DocSpace-files-services (start)
DocSpace-files (failed)
DocSpace-healthchecks
DocSpace-login
DocSpace-notify (start)
DocSpace-people-server (failed)
DocSpace-socket
DocSpace-ssoauth
DocSpace-studio-notify (start)
DocSpace-studio
Docs Converter
Docs Docservice
Docs Metrics
What services are necessary to recover the system or can I extract the docs from the file system?

**Comment by ldwnt** [comment]
> Did you install Workspace or Docspace? And what type of installation are you using - docker or deb packages?

Sorry, my description about the installation script was wrong. I did install Docspace, not Workspace. And I followed this guide: https://helpcenter.onlyoffice.com/installation/docspace-community-install-script.aspx. The machine is not with me right now, but since I used a VM, I think the installation was done using deb packages instead of docker. I'll check it on tomorrow.

**Comment by ldwnt** [comment]
> Did you install Workspace or Docspace? And what type of installation are you using - docker or deb packages?

I confirm it was installed using the command: bash docspace-install.sh package
The VM has 10GB memory and 8 cores

**Comment by Carazyda** [comment]
And all the memory is used? Try increasing it to 16 GB (the minimum requirement for Docspace).

**Comment by ldwnt** [comment]
> And all the memory is used? Try increasing it to 16 GB (the minimum requirement for Docspace).

Memory is not the problem in my case. It returns 502 because the following services are down:
docspace-api
docspace-files
docspace-people-server
mysql

How do I recover these services or how do I extract my docs from the file system?

**Comment by Carazyda** [comment]
These services are not running, possibly due to low memory. Try restarting them manually. Also check the status and errors for these services.

The files are located in `/var/www/onlyoffice/Data/Products/Files`.

**Comment by ldwnt** [comment]
> These services are not running, possibly due to low memory. Try restarting them manually. Also check the status and errors for these services.
> 
> The files are located in `/var/www/onlyoffice/Data/Products/Files`.

Thanks for the information. Is it possible that I create a clean VM with docspace installed and copy the files under /var/www/onlyoffice/Data/Products/Files from the old VM to the new VM and recover the docspace?

**Comment by Carazyda** [comment]
Sorry, but you can't copy just files. You also need a database dump for it to work properly. The best way is to backup your portal via settings.
