### ISSUE TITLE
Message delivery failure

### ISSUE THREAD

**Issue by Ventajou** [ONLYOFFICE/CommunityServer#54]
Hi,

I installed OnlyOffice on docker using http://download.onlyoffice.com/install/opensource-install.sh and configured my DNS for email to the point that everything is green in the Mail settings. But whenever I try to send an email, I get a `Message delivery failure` with no information to troubleshoot except for `Reason: "Smtp."`

I also try sending emails to my server and I see them come through in the postfix log on the mail container but they never show up in the web UI...

**Comment by AlexeySafronov** [comment]
Hi.

Try to find more info in /var/log/onlyoffice/web.api.log inside onlyoffice-communityserver container.

**Comment by Ventajou** [comment]
I figured it out, the default config relies on the mail domain name to resolve the SMTP server, which correspond to the external IP of the Docker host. But the firewall on the host was blocking the port when the community server container attempted to connect. I didn't expect that because I didn't have the issue from a remote machine.
