### ISSUE TITLE
Custom DNS breaks Reverse proxy configuration and activation emails.

### ISSUE THREAD

**Issue by ambroisemaupate** [ONLYOFFICE/CommunityServer#55]
Hi Team!

I’ve setup *Community Server* using *Docker* on custom ports instead of `80` and `443` to be able to install other apps on our Linux server.

```shell
onlyoffice-community-server   onlyoffice4enterprise/communityserver-ee:8.9.2.27   3306/tcp, 5280/tcp, 9865-9866/tcp, 9871/tcp, 9882/tcp, 9888/tcp, 0.0.0.0:5222->5222/tcp, 0.0.0.0:8081->80/tcp, 0.0.0.0:4431->443/tcp
```

I’ve used an Apache Proxy virtual host to redirect to the container (we only need community server, no mail server, no document server).

- If I set the `Custom DNS` setting to our hostname (`https://onlyoffice.xxxxxx.com`), this breaks mailing system and *activation email links*.
- If I don’t set it, I get wrong *activation email link*. This seems legit because we are inside a Docker container. `450042771ab5` is the container internal hostname.

```
http://450042771ab5:8081/confirm.aspx?type=Activation
```

So the problem is why does OnlyOffice breaks my outgoing emails when I set `Custom DNS` ? Because I don’t want my users to edit manually their activation URL with the real hostname and port.

Here is my Apache configuration to proxy to the Docker *Community Server* container.

```apache
<VirtualHost *:80>
    ServerAdmin xxxxxxxxxxxx
    ServerName onlyoffice.xxxxxx.com

    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName onlyoffice.xxxxxx.com
    ServerAdmin xxxxxxxxxxxx

    ProxyPass / http://localhost:8081/
    ProxyPassReverse / http://localhost:8081/

	SSLEngine on
	SSLCertificateFile /etc/letsencrypt/live/onlyoffice.xxxxxx.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/onlyoffice.xxxxxx.com/privkey.pem
        SSLCertificateChainFile /etc/letsencrypt/lets-encrypt-x3-cross-signed.pem
</VirtualHost>
</IfModule>
```

Thanks for your help.

**Comment by JohnPerkin** [comment]
Hello!
Open in your portal Settings > Common > Customization and set your domain name in the field 'Custom Domain Name' as it is done on the [screenshot](http://take.ms/FShvz). Then send activation link without setting custom DNS in your Apache configuration.
Feel free to contact us here if you will have any questions or suggestions.

**Comment by ambroisemaupate** [comment]
Hi, Thanks for you answer,

As a matter of fact, I was using *Custom Domain Name* feature in OnlyOffice: this is breaking mailing system and activation email links. 

When I disables it, everything works fine but URL in the email is generated with the local hostname and port.

For the moment I tell my coworker to replace the docker hostname and port by the real hostname and activation link is OK.

**Comment by JohnPerkin** [comment]
Hello!
Please give us more information about your network configuration and server's place in it. 
Also describe in details what does it mean?
> breaks mailing system and activation email links

**Comment by eqmo** [comment]
Use the full domain name in the ProxyPass and ProxyPassReverse parameters.

ProxyPass / http://subdomain.domain.com:8081/
ProxyPassReverse / http://subdomain.domain.com:8081/

And add to /etc/hosts the entry in the proxy machine.

127.0.0.1 subdomain.domain.com

That solve a similar problem for me.

**Comment by ambroisemaupate** [comment]
That’s a bit better @eqmo . Emails are now generated with the right domain name but it still keeps the internal port instead of forwarded port and prototype.

Onlyoffice generate urls with `http://subdomain.domain.com:8081/` instead of `https://subdomain.domain.com`

Here is my Apache conf:

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName subdomain.domain.com

    ProxyPass / http://subdomain.domain.com:8081/
    ProxyPassReverse / http://subdomain.domain.com:8081/

        SSLEngine on
        SSLCertificateFile /etc/letsencrypt/live/subdomain.domain.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/subdomain.domain.com/privkey.pem
        SSLCertificateChainFile /etc/letsencrypt/lets-encrypt-x3-cross-signed.pem
</VirtualHost>
</IfModule>
```

**Comment by eqmo** [comment]
Try to add : 

**ProxyPreserveHost On**

after the ServerName subdomain.domain.com
I use nguni for the reverse proxy, but I think this should work for you.

**Comment by ambroisemaupate** [comment]
Thanks @eqmo. Now url in email are generated with `http://subdomain.domain.com`. There is no `https` but that’s not a big deal I’ve set an automatic redirect to SSL.

**Comment by ambroisemaupate** [comment]
After several weeks, this option made OnlyOffice really slow for each tasks that send email notifications. 

Each time we save a project, task or person object, the loader is showing for infinite time and when we hard-reload page, changes have been well saved.

**Comment by eqmo** [comment]
Hi, I attach the sections from the nginx config file. I don't know the equivalent for apache, but as it is, only office doesn't have any speed issue. Additionally I add the mail server to the /etc/hosts file as well.

![config](https://cloud.githubusercontent.com/assets/11879293/26313097/5f36cef0-3f3c-11e7-8353-9b697a8aeb2d.jpg)

**Comment by elodiearnouk** [comment]
I second @ambroisemaupate on the speed. Persistent time out errors and saving issues (video below - 1 min long loader before time out). Ever since the change was made, the solution became a project management nightmare and there's no way out it seems.
Any suggestions on how to get back to normal? 

![1min time out](https://cloud.githubusercontent.com/assets/19607651/26682226/fc446d56-46df-11e7-89e6-f30074bbfcac.gif)

**Comment by eqmo** [comment]
Could you send or pastern the entire flow? HAR file to check on which request the page stall.

**Comment by elodiearnouk** [comment]
There you go: https://pastebin.com/xCJhQe96

**Comment by ambroisemaupate** [comment]
Response timeout issue seems to be gone after upgrading to latest CommunityServer Docker image version (v9.0.0.300).

**Comment by elodiearnouk** [comment]
Thank you all!! :)
