### ISSUE TITLE
I18n issue - French

### ISSUE THREAD

**Issue by ambroisemaupate** [ONLYOFFICE/CommunityServer#56]
French translation issue in Gantt chart module.

![capture d ecran 2017-03-06 a 09 43 34](https://cloud.githubusercontent.com/assets/380026/23602582/855d816e-0251-11e7-80e9-145f420fe51a.png)

`Time scale` in Gantt chart module: *Échelle chronologique*

**Comment by JohnPerkin** [comment]
Hello!
We took it in consideration, the error will be corrected in the new release of Community Server.
You may change the spelling in the current version: attach Community Server container, enter mysql and open database 'onlyoffice'. Then change the value using the following command:
`UPDATE res_data SET textvalue='Échelle chronologique' WHERE title = 'GanttTimelineScale' AND cultureTitle = 'fr';`
Thank you for the interest in ONLYOFFICE.
