### ISSUE TITLE
MySQL failure during Install on Ubuntu 14.04

### ISSUE THREAD

**Issue by vCentre** [ONLYOFFICE/CommunityServer#58]
Please advice on the below error,
Installation always getting aborted with clean install on Ubuntu 14.04

ERRORERROR 1045 (28000) 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

root/onlyoffice passwords were entered correctly during install

I have tried install on Windows 2008 R2, 2016 and ending with failure too, MySQL wizard does not appear during install to provide root/database name/password etc. details
MySQL were installed manually before launching installation wizard but failed too; I guess because the most frustrated and IIS server.

Please revise and advice!

**Comment by JohnPerkin** [comment]
Hello!
Please try to connect directly to the onlyoffice database
`mysql -D "onlyoffice" -u<username> -p<password>`
Check if there is a connection to mysql
`service mysql status`
If the connection is not established change the necessary values in files **/var/www/onlyoffice/WebStudio/web.connections.config** and **/var/www/onlyoffice/WebStudio2/web.connections.config**. Then restart Community Server with the following commands
```
service monoserve restart
service monoserve2 restart
```
