### ISSUE TITLE
Calendar event add error

### ISSUE THREAD

**Issue by eqmo** [ONLYOFFICE/CommunityServer#62]
After upgrade the version using docker, I start recieving this error message when I add an event to the calendar

Table 'onlyoffice.calendar_event_history' doesn't exist

**Comment by andreysavihin** [comment]
Could you please specify which Community Server version you are trying to upgrade and to which version? You will need to run SQL scripts to update the database. Please go to the https://github.com/ONLYOFFICE/CommunityServer/tree/master/build/sql folder and run all the scripts from there one-by-one, starting with the version you are going to update from, and finishing with the version you want to get in the end.

**Comment by eqmo** [comment]
I move the data from 8.6.0.24 to 8.9.1.191, can you help to know which scripts should I run and How to run it. My community and Document server are running on Docker. Thanks

**Comment by JohnPerkin** [comment]
Hello @eqmo!
Please download the scripts from the link above beginning with `'onlyoffice.upgrade86.sql'` to `'onlyoffice.upgrade892.sql'`
Copy them into Community Server container with the command `'docker cp script_name.sql container_id:/directory/'`
Attach the container using `'docker exec -it container_id bash'`
Then execute all of them by turn with `'mysql -D "onlyoffice" < script_name.sql'`
At the end reboot the container with `'docker restart container_id'.`

**Comment by eqmo** [comment]
I just run the scripts and the problem was solved. Thank you.
