### ISSUE TITLE
Request: customize "Anonymous" name when editing a document.

### ISSUE THREAD

**Issue by Libeccio84** [ONLYOFFICE/CommunityServer#64]
I am integrating the document iframe in a confluence page, in order to let other people edit a document directly from confluence.
It works fine, but it would be nice to give users the possibility to change "Anonymous" to their name.
Is this feature available/feasible?

Many thanks

**Comment by JohnPerkin** [comment]
hello @Libeccio84!
Explain how exactly to transmit names of users from Confluence to Community Server to display them in Document Server?
Please pay attention to our [Confluence integration plugin](https://api.onlyoffice.com/editors/confluence)

**Comment by LinneyS** [comment]
Fixed ONLYOFFICE/onlyoffice-confluence#3
