### ISSUE TITLE
Lack of "paste special" nor paste without formatting

### ISSUE THREAD

**Issue by arjamizo** [ONLYOFFICE/CommunityServer#65]
In Google Docs pasting without formatting works under `Ctrl+Shift+V`, there is also such an option in Microsoft Office, but in OnlyOffice one has to paste and then clear formatting.

**Comment by ibnpetr** [comment]
Hello 
In ONLYOFFICE Document Server v. >4.4.1 when you paste a text you have an option to control the formatting 
You also can copy and paste the formatting using Ctrl+Shift+C / Ctrl+Shift+V (like you do it in MS Office)
![new document docx - google chrome 2017-07-11 11 13 56](https://user-images.githubusercontent.com/16033936/28059020-71956a46-662b-11e7-91bd-aa0c9e2ef992.png)
Please note that this issue should be posted [in the Document Server repo](https://github.com/ONLYOFFICE/DocumentServer)

**Comment by geomorillo** [comment]
Ctrl+Shift+V  works

**Comment by risacher** [comment]
If I copy from another application (Google Chrome), and try to paste into ONLYOFFICE, Ctrl-Shift-V does nothing.

**Comment by Carazyda** [comment]
Hello @risacher if you have any problems with onlyoffice desktop editors - please open issue in this [repo](https://github.com/ONLYOFFICE/DesktopEditors/).

**Comment by dziq88** [comment]
I have the same issue. Ctrl+Shift+V for paste text only is default for me. Same as double-click and drag to select whole words.
Now it works rather quirky. It would be great to be able to customize shortcuts.
Don't get me wrong - I love your editor. Keep it up guys! :)

**Comment by Carazyda** [comment]
Hello @dziq88 Thank for your feedback. If you have any problems with onlyoffice desktop editors - please open issue in this [repo](https://github.com/ONLYOFFICE/DesktopEditors/).
