### ISSUE TITLE
Does not properly open excel spreadsheet

### ISSUE THREAD

**Issue by b09dan** [ONLYOFFICE/CommunityServer#66]
Onlyoffice community server does not properly open excel spreadsheet with fixed row and column.
The file and screenshots are stored by the following link: https://goo.gl/p1MqZi
![_051](https://user-images.githubusercontent.com/17816777/28258587-9f6a47d0-6ada-11e7-8c2c-1f0b6d0f66a3.png)

**Comment by b09dan** [comment]
I have found, that if I this big white squares (objects) are deleted(there are a lot of them, one over another), whole document displays fine, so, I suppose the main problem is with color fill, that somehow displays as an object only in onlyoffice.

**Comment by trofim24** [comment]
These were hidden shapes. We'll fix it in the next releases.

**Comment by b09dan** [comment]
@trofim24 ok, thanks for reply! Good luck to your project!
