### ISSUE TITLE
Некоректно импортируются контакты с несколькими телефонами или email адресами.

### ISSUE THREAD

**Issue by laigor** [ONLYOFFICE/CommunityServer#68]
1. Создаю компанию с несколькими рабочими телефонами:
![_2017-08-08_12-41-51](https://user-images.githubusercontent.com/5516812/29169525-1f902dd4-7ddd-11e7-8149-203d46146ef2.png)
2. Экспортирую в csv.
3. Удаляю компанию
4. Импортирую csv файл из пункта 2 и получаю такой результат:
![_2017-08-08_13-01-25](https://user-images.githubusercontent.com/5516812/29169527-1f942876-7ddd-11e7-9576-748e3398a101.png)

**Comment by ibnpetr** [comment]
Hello 
Thanks for the information
We found the issue, it will be fixed in the next version.
