### ISSUE TITLE
Поправить верстку окна прав доступа

### ISSUE THREAD

**Issue by realkot** [ONLYOFFICE/CommunityServer#70]
Google Chrome Версия 61.0.3163.79 (Официальная сборка), (64 бит), при открытии окна прав доступа к документу обрезается правая сторона окна:
![image](https://user-images.githubusercontent.com/24507273/30249443-72f118e6-9645-11e7-9e7a-4aeff03b7055.png)

В Firefox Developer Edition 56.0b10 (64-бит) в этом же окне под кнопкой "Закрыть" большое пустое пространство:
![screenshot 46](https://user-images.githubusercontent.com/24507273/30249432-3ea63f12-9645-11e7-996f-cf3c210eda40.jpg)

В IE аналогичная FF проблема:
![image](https://user-images.githubusercontent.com/24507273/30249482-10a1e854-9646-11e7-8368-28460461ef38.png)

**Comment by LinneyS** [comment]
В Chrome установлен масштаб 125%.
В FireFox и IE отображается корректно. Лишнее пространство внизу уходит при включении доступа по ссылке и изменении списка пользователей. В следующей версии Community изменение размера по высоте уже исправлено.
