### ISSUE TITLE
Facing problem in compiling and deploying

### ISSUE THREAD

**Issue by rajat10** [ONLYOFFICE/CommunityServer#71]
I have checked out this code on my local (Win 10 pro x64), installed visual studio 2017. Created database and followed all the procedures provided on http://helpcenter.onlyoffice.com/server/windows/community/compile-source-code.aspx
while running BuildAndDeploy.bat (located in  \CommunityServer-master\build\) I got these errors.

![comunity_server_compiling_error](https://user-images.githubusercontent.com/7193717/30429025-878890aa-9973-11e7-83a4-0cdc7087aaeb.PNG)

please help me to resolve this issues or tell me the compatible windows and .net framework version on which I can compile and deploy it.

**Comment by alexeybannov** [comment]
Development ahead of the documentation. Please install Microsoft .NET Framework 4.6.2
