### ISSUE TITLE
BUG. Errore when saving document when in folder name "&"

### ISSUE THREAD

**Issue by realkot** [ONLYOFFICE/CommunityServer#73]
BUG.
Errore when saving document in folder name "&".

Example:
- folder with name "Formulas & Validations":
![image](https://user-images.githubusercontent.com/24507273/30759443-d40c9e3c-9fde-11e7-88fd-3d2f2fdf5323.png)

- when rename to "Formulas and Validations" problem is gone

**Comment by LinneyS** [comment]
Thanks a lot for your interest in our product, your experience is important for us.
Fixed
