### ISSUE TITLE
CRM. Problems with E-mails

### ISSUE THREAD

**Issue by realkot** [ONLYOFFICE/CommunityServer#74]
E-mails` doesn't sent to *@*.life domains

`Request URL:https://lk.kudrovo.life/api/2.0/crm/settings/testmail.json?__=397421
Request Method:POST
Status Code:500 
Remote Address:31.134.141.199:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
cache-control:private, max-age=0
content-length:173
content-type:application/json; charset=UTF-8
date:Sun, 24 Sep 2017 18:19:22 GMT
etag:c221cf8a009e416cbcadd1eb8f4a4b22
server:nginx
status:500
strict-transport-security:max-age=31536000; includeSubDomains; preload
strict-transport-security:max-age=15768000; includeSubDomains; preload
via:2.0 lk.kudrovo.life (Apache/2.4.27)
x-aspnet-version:4.0.30319
Request Headers
:authority:lk.kudrovo.life
:method:POST
:path:/api/2.0/crm/settings/testmail.json?__=397421
:scheme:https
accept:application/json, text/javascript, */*; q=0.01
accept-encoding:gzip, deflate, br
accept-language:ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
content-length:307
content-type:application/x-www-form-urlencoded; charset=UTF-8
cookie:_ym_uid=1501581714198722618; is_retina=true; tmtalk=ver:2.0::sndbyctrlentr:1; asc_auth_key=Qw+XAFGyoYrYzQDuSFFipDBXOIYhfwcXmOAZDNR/9jXLODa2s5RSQw/rZfQDQSo/63CTGK2zGc5HhuPsXsXB/9yxYj3v+8VamQh5hhW7aHxFSlfyp9U07ohnhrXPyhCq3WRIFjWDB/WDHZskKhUrBQ==; wmt_secToken=Wc4ca4238a0b923820dcc509a6f75849bS|1; ASP.NET_SessionId=301EA3C02AF8D78B1AFD4C82; _ga=GA1.2.1780707388.1501283584; _gid=GA1.2.123652834.1506188433; colorname_c=Wc4ca4238a0b923820dcc509a6f75849bS|1; colorname_e=Wc4ca4238a0b923820dcc509a6f75849bS|1; colorname_p=Wc4ca4238a0b923820dcc509a6f75849bS|1; _ym_isad=2; _ym_visorc_36652330=w; %2F=%5B%22open%22%2C%22%22%2C%22%22%2C%22open%22%2C%22%22%2C%22%22%2C%22open%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%2C%22%22%5D
dnt:1
origin:https://lk.kudrovo.life
referer:https://lk.kudrovo.life/products/crm/settings.aspx
user-agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
x-requested-with:XMLHttpRequest
Query String Parameters
view source
view URL encoded
__:397421
Form Data
view source
view URL encoded
toEmail:admin@kudrovo.life
mailSubj:TEST
mailBody:This is a test mail message created by the ONLYOFFICE portal automatically to check the mass mailing feature.
Please do not reply to this message.

We are sorry for any inconveniences caused.
Best regards,
Portal lk.kudrovo.life administration`

`{status: 1, statusCode: 500,…}
error
:
{message: "Некорректный адрес электронной почты: admin@kudrovo.life", hresult: -2146233088, data: {}}
data
:
{}
hresult
:
-2146233088
message
:
"Некорректный адрес электронной почты: admin@kudrovo.life"
status
:
1
statusCode
:
500`

`{"status":1,"statusCode":500,"error":{"message":"Некорректный адрес электронной почты: admin@kudrovo.life","hresult":-2146233088,"data":{}}}`

In console: head-qKKlw6WNe5umHng4LZvf8A2.js?ver=9.1.1.418:2 POST https://lk.kudrovo.life/api/2.0/crm/settings/testmail.json?__=397421 500 ()

When sent to the another test mail login165@yandex.ru CRM write that mail was sent but mail doesn't received.

**Comment by andreysavihin** [comment]
The problem is resolved. Wait for the release of the new version.
