### ISSUE TITLE
Erreur Inconnue when create or editing document

### ISSUE THREAD

**Issue by ychoucha** [ONLYOFFICE/CommunityServer#77]
Hello, 
i m on a frech install using docker on ubuntu 16.04.

using this how to --> https://www.linuxbabe.com/linux-server/install-onlyoffice-ubuntu-16-04

my probleme is when i try to create a document i have this error : 

![image](https://user-images.githubusercontent.com/301074/31532611-a0fd2398-afee-11e7-9e3c-4274a07009e0.png)

can u please helpe me to found how debug this probleme

thanks

**Comment by alexeybannov** [comment]
Please use this spript http://download.onlyoffice.com/install/opensource-install.sh to install ONLYOFFICE Community Edition.

**Comment by ychoucha** [comment]
Hello

But with thé script we don t have HTTPS activated

**Comment by ychoucha** [comment]
Ok so now i have installed nginx, but i need to know how change the port of onlyoficce?


this my nginx conf files : 

`server {
        listen 80;
        server_name oo.demo.com;
        return 301 https://$server_name$request_uri;
}

server {
        listen 443 ssl http2;
        server_name oo.demo.com;

       ssl                  on;
       ssl_certificate      /etc/ssl/oo.demo.com/oo.demo.com.crt;
       ssl_certificate_key  /etc/ssl/oo.demo.com/oo.demo.com.key;

        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:10m;
        ssl_session_tickets off;
        ssl_protocols TLSv1.1 TLSv1.2;


        error_log /var/log/nginx/onlyoffice.error;
        access_log /var/log/nginx/onlyoffice.access;

        location / {
                proxy_pass http://127.0.0.1:8080;
        }

}

`

so do u know how configre the nginx to go on onlyoffice in port 80 ?

thanks

**Comment by alexeybannov** [comment]
After installing according to instructions http://download.onlyoffice.com/install/opensource-install.sh,  put the certificates on the path 
/app/onlyoffice/CommunityServer/data/certs/onlyoffice.key
/app/onlyoffice/CommunityServer/data/certs/onlyoffice.crt 
and restart container CommunityServer.

**Comment by ychoucha** [comment]
Hello, 

so i do this simple task : 

1> Install frech ubuntu server 16.04 LTS
2> Install OnlyOffice with script : 
         -  wget http://download.onlyoffice.com/install/opensource-install.sh
         -  bash opensource-install.sh -md "yourdomain.com"
3> Create my own ssl certificate : 
         - domaine=oo.mydmoine.com
         - cd /etc/ssl
         - mkdir $domaine
         - cd $domaine
         - openssl genrsa -out $domaine.key 2048
         - openssl req -new -key $domaine.key -out $domaine.csr
         - openssl x509 -req -days 365 -in $domaine.csr -signkey $domaine.key -out $domaine.crt
4> Copy certificat files on docker onlyOffice : 
         - cp /etc/ssl/$domaine.key ./app/onlyoffice/CommunityServer/data/certs/onlyoffice.key
         - cp /etc/ssl/$domaine.crt /app/onlyoffice/CommunityServer/data/certs/onlyoffice.crt

5> restart docker community 
        - found docker id with 
                   - docker ps
        - restart the cdocker community  :
                  - docker restart b510353c2b25

6> go to web access  https://yourdomain.com
and works 

thanks !!!!
