### ISSUE TITLE
OnlyOffice still in english, but choice is french :

### ISSUE THREAD

**Issue by ychoucha** [ONLYOFFICE/CommunityServer#78]
Hello i have just installed the docker comunity version : 

so my configuration is in french : 
![image](https://user-images.githubusercontent.com/301074/31603610-f8e9169c-b260-11e7-8c80-894bd00bb771.png)

but all my onlyOffice is in english, why the language is not in french after changing this parameter

thanks to all

**Comment by LinneyS** [comment]
You can change your language on profile page
and you can change the language on the settings page for all users (your screen)
Please check your profile page _products/people/profile.aspx_

**Comment by ychoucha** [comment]
My profil page is FRENCH, 
but onlyOffice is still in english

![image](https://user-images.githubusercontent.com/301074/31611122-1b8c14b4-b27b-11e7-9905-20cf6dc506ee.png)

interface in english : 
![image](https://user-images.githubusercontent.com/301074/31611136-26c8bf30-b27b-11e7-9e07-1d7bf69ef300.png)

**Comment by LinneyS** [comment]
The problem is repeated with other languages? For example, German?

**Comment by ychoucha** [comment]
Yes

the german i selected,but evrything is in english

**Comment by alexanderonlyoffice** [comment]
@ychoucha, please try to restart the community server container. If this does not help, try to re-install the product.

**Comment by ychoucha** [comment]
ok works with a reinstall.

can we add a sharing windows diretly in onlyoffice access ?

how sync files to onlyoffice and windows directory share ?

Exemple : 

i works on many document like this : 

//filesServer01/Documents/cafe/Ambra

how access directly on this directory and add and remove files directly from onlyOffice ?


thanks

**Comment by alexanderonlyoffice** [comment]
@ychoucha, please set up access to windows folders/directories through WebDAV.

**Comment by ychoucha** [comment]
Hello, 
thanks, but not working : 

![image](https://user-images.githubusercontent.com/301074/31770030-61ee6774-b4d6-11e7-9e4e-6b7d631cc0e4.png)

**Comment by LinneyS** [comment]
Open new issue with this question
