### ISSUE TITLE
Windows sharing directly acces on onlyoffice

### ISSUE THREAD

**Issue by ychoucha** [ONLYOFFICE/CommunityServer#79]
Hello there 

can we add a sharing windows diretly in onlyoffice access ?

how sync files to onlyoffice and windows directory share ?

Exemple :

i works on many document like this :

//filesServer01/Documents/cafe/Ambra

how access directly on this directory and add, edit or remove files directly from onlyOffice ?

i have try with webDav acces, but not working : 

![image](https://user-images.githubusercontent.com/301074/31770107-b17231ae-b4d6-11e7-8849-c3769a1462f1.png)

do u know how do that please ?

thanks

**Comment by LinneyS** [comment]
You use WebDav or FTP ?

**Comment by ychoucha** [comment]
No FTP, nom webDav. Only windows sharing with authentification

**Comment by LinneyS** [comment]
ONLYOFFICE not support SMB Protocol.
Please use WebDav for this task

**Comment by ychoucha** [comment]
i don't have it
:/

**Comment by alexanderonlyoffice** [comment]
@ychoucha, you should set up WebDAV Server in Windows.

**Comment by ychoucha** [comment]
Do u have an application name  to be sûre compatible with onlyoffice ans works with active directory login

**Comment by alexeybannov** [comment]
For example, you can configure an IIS application as a webDAV server  http://bit.ly/2gogFMd and then mount the local folder to onlyoffice.

**Comment by alexeybannov** [comment]
Integration with ADFS available in the paid version of onlyoffice.

**Comment by ychoucha** [comment]
onlyOffice looks cool 👍

but i see this page : https://www.onlyoffice.com/fr/compare-server-editions.aspx

only 20 user Max, i think i can't continue to use onlyoffice :'(

**Comment by alexeybannov** [comment]
The maximum number of users in Community Edition is the amount of users that can collaboratively edit documents.

**Comment by ychoucha** [comment]
that' means, i can create 100 users ?

and if i can i have in the same time : 

- 5 users working on XLS files
- 10 users workging on docx
- 2 users on a PPT files
- 3 users on an other ppt files
so we have 20 users works on collaboratively but not on the same files ?
in the exemple can other user can works on the same files ?

**Comment by ibnpetr** [comment]
@ychoucha 
Community Edition has a limitation in 20 editing sessions.
In other words, it is better to speak about the active editing sessions:
1 users is editing 5 documents - 5 sessions are active.
other 5 users are editing a single document in the co-editing mode - 5 sessions are active.

**Comment by ajl000** [comment]
Um I tried webdav through IIS ... didn't work with enterprise edition.  Support couldn't get it to work either.  Don't get your hopes up.

**Comment by Spartacus2018** [comment]
Hello,

@ajl000 can u details how that's works please, i m interesting to do this

**Comment by ajl000** [comment]
sure I can show you - skype adamjameslaw  Perth time, Australia.
If you have a friend who does even a bit of coding, they should be able to
set it up for you.

**Comment by ajl000** [comment]
There is only one caveat, you have to have all users editing the files
through OnlyOffice.

Updates directly to the file on say c:\....\  will cause issues with saving.
