### ISSUE TITLE
Using this with visual studio

### ISSUE THREAD

**Issue by ajaythedeveloper** [ONLYOFFICE/CommunityServer#8]
How can we use this with visual studio

**Comment by AnaMih** [comment]
You may download the source code and open the projects files using VS. For example https://github.com/ONLYOFFICE/ONLYOFFICE-Server/blob/master/common/ASC.Common/ASC.Common.csproj

**Comment by Tatoo988** [comment]
i've done what you said but still not working. it gots too much csproj files to add them one by one. how can i mount a solution including all this components and compiling?

**Comment by Tatoo988** [comment]
Parser Error Message: Could not load type 'ASC.Web.Studio.HttpHandlers.JwtHandler' from assembly 'ASC.Web.Studio'.

Line 93:       <add verb="POST,GET" path="jwtlogin.ashx" type="ASC.Web.Studio.HttpHandlers.JwtHandler, ASC.Web.Studio" />

if i comment that line i get the same for 

Line 94:       <add verb="POST,GET" path="samllogin.ashx" type="ASC.Web.Studio.HttpHandlers.SamlHandler, ASC.Web.Studio" />

**Comment by AnaMih** [comment]
There is no common sln file for Vs. A prоject can be builded by using script from "build" catalog or you may explore dependencies and add projects to sln.
