### ISSUE TITLE
Its possible to compile for freebsd?

### ISSUE THREAD

**Issue by felixgonsug** [ONLYOFFICE/CommunityServer#84]
Im wondering to deploy onlyoffice in companion with nextcloud on freebsd

**Comment by ibnpetr** [comment]
Hello 
Unfortunately Document Server cannot be installed on freebsd
Anyway, if you are interested in using Document Server with Nextcloud we would recommend to try working with our [Integration application](https://www.onlyoffice.com/connectors-nextcloud.aspx) that will allow you to connect Document Server to your Nextcloud.
Please feel free to post the question in the [appropriate section](https://github.com/ONLYOFFICE/onlyoffice-owncloud)
