### ISSUE TITLE
Can't Edit a File Online

### ISSUE THREAD

**Issue by hmwangi** [ONLYOFFICE/CommunityServer#85]
I'm having problems editing a file online using the community server. When I click on the file, it downloads instead. Any help/tips to fix this will be highly appreciated.

Regards

**Comment by alexeybannov** [comment]
You have installed ONLYOFFICE Document Server? Use our bash script to install ONLYOFFICE Community Editions: http://download.onlyoffice.com/install/opensource-install.sh
