### ISSUE TITLE
Not able to install community server 

### ISSUE THREAD

**Issue by arunksasi** [ONLYOFFICE/CommunityServer#86]
Hi Iam getting below error while installing only office community server , can u help me on this ?

ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by ibnpetr** [comment]
Hello 
Please specify the type of installation and your operating system.
Are you trying to install the product using the [instructions from our help center](http://helpcenter.onlyoffice.com/server/community.aspx)?

**Comment by arunksasi** [comment]
Hi, This issue has been fixed , I had  used wrong mysql password.I have reset mysql password to what I had given while installing only office community server .
Thanks for your response .
