### ISSUE TITLE
Problem integration with DocumentServer

### ISSUE THREAD

**Issue by malatny** [ONLYOFFICE/CommunityServer#94]
I have two servers CommunityServer and DocumentsServer,  without JSON web token validation key work fine. I do not know where to enter in CommunityServer config JSON web token validation key

**Comment by ibnpetr** [comment]
The value 
<add key="files.docservice.secret" value="YOUR_SECRET" />
should be changed in the 
 /var/www/onlyoffice/WebStudio/web.appsettings.config

**Comment by malatny** [comment]
Thank you very much

2018-03-07 13:38 GMT+01:00 Alexey Mikheev <notifications@github.com>:
