### ISSUE TITLE
communication with Document Server - Command url: Error: ConnectFailure (Connection refused),[object Object]

### ISSUE THREAD

**Issue by ndecaris** [ONLYOFFICE/CommunityServer#97]
hi everyone,

OO community Server is installed on debian with apt command with the latest version
OO Document Server is installed on another debian server with apt command with the latest version (5.1.4)

From a nextcloud server we can use Document server for edit AND modify document.
But From OO community server, we just can edit Document, we can't modify documents.

in parameters panel of OO Community Server, in section "Document Service", we configure URLs to get access to document server and the URL to get back and save/store document on the community server. when we save settings, we got this message : "Command url: Error: ConnectFailure (Connection refused),[object Object]"

a trace with tcpdump, shows that HTTPS is initiated from Document Server to Community Server, but reset from Community Server without reason.

can someone help us to find a way so that it could work .....

thank you in advance

**Comment by ibnpetr** [comment]
> we just can **edit** Document, we can't **modify** documents.

Please specify what do you mean by "modify"

> we configure URLs to get access to document server and the URL to get back and save/store document on the community server.
 
Please make sure that the address of the Document Server is available from the Community Server.

**Comment by ndecaris** [comment]
oh **modify** means :  save the modification of a document

Document Server is available for Community Server. In fact, the problem is in the other way, from DS to CS. 

i add some configuration in file "web.appsettings.config" as documentation at this [url](https://helpcenter.onlyoffice.com/server/linux/document/connect-document-server.aspx) specify !!

wget from Document Server to Community Server works !

the only message is when i save settings in panel parameters -> 'Document Server", the error is in object of this issue : **Command url: Error: ConnectFailure (Connection refused),[object Object]**

**Comment by ndecaris** [comment]
sorry for disturbing the crew. bu tin fact, configuration in file "web.aapsettings.config" was wrong.
everything is OK now.
