### ISSUE TITLE
Backup - how to make a total backup (configuration and user data)

### ISSUE THREAD

**Issue by ndecaris** [ONLYOFFICE/CommunityServer#98]
Hello onlyoffice folks,

i was looking for a complete backup for OnlyOffice Community Server.
when i say "complete", i mean : configuration (parameters) and user data (document, mails, crm database, ...).

thank you in advance.
Nicolas

**Comment by alexanderonlyoffice** [comment]
Hello @ndecaris,

If you are using Docker installation, it is enough to copy mounted folder /app/onlyoffice

If it is a DEB/RPM installation, you have to copy the following folders: with files /var/www/onlyoffice/Data and with all parameters /var/www/onlyoffice/Services and /var/www/onlyoffice/WebStudio, make DB dump and copy all nginx configs. 

The easiest way to backup your portal is to use [Control Panel](https://helpcenter.onlyoffice.com/server/controlpanel/enterprise/backup-restore.aspx), which a part of Enterprise Edition. Please follow this [link](https://www.onlyoffice.com/server-solutions.aspx) to find more information about this product.

**Comment by ndecaris** [comment]
thank you alexander

we will follow your advice, and having a try for a restore operation to be sure everything is fine !!
